{{- if .Values.networkPolicies.enabled }}
---
# Allow `cluster-claim-operator-controller-manager` to talk to the Kubernetes API server.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-cluster-claim-operator-to-kube-apiserver-6443
  namespace: {{ include "cluster-claim-operator.namespaceName" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "cluster-claim-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
      k8s:io.kubernetes.pod.namespace: {{ include "cluster-claim-operator.namespaceName" . }}
  egress:
  - toEntities:
    - world
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from cluster-claim-operator-controller-manager to the
    Kubernetes API server on 6443 for control-plane interactions.
{{- end }}
