apiVersion: v2
name: addon-operator
description: A Helm chart to distribute the project addon-operator
type: application
version: 0.1.6
appVersion: "v0.0.8-dd63afe5"
icon: "https://example.com/icon.png"
