apiVersion: v2
name: addon-operator
description: A Helm chart to distribute the project addon-operator
type: application
version: 0.1.3
appVersion: "v0.0.4-12e5009a"
icon: "https://example.com/icon.png"
