apiVersion: v2
name: addon-operator
description: A Helm chart to distribute the project addon-operator
type: application
version: 0.1.4
appVersion: "v0.0.4-bf6aa5c2"
icon: "https://example.com/icon.png"
