apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base.yaml

patches:
  - path: ./deployment.vm-operator-victoria-metrics-operator.yaml
    target:
      kind: Deployment
      name: vm-operator-victoria-metrics-operator

  - path: ./service.vm-operator-victoria-metrics-operator.yaml
    target:
      kind: Service
      name: vm-operator-victoria-metrics-operator
