---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: capi-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: capi  
spec:
  values: ""

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: capi-vm-operator
  labels:
    addons.in-cloud.io/values: vm-operator
    addons.in-cloud.io/addon: capi
spec:
  values: |
    monitoring:
      vmServiceScrape:
        enabled: true

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: capi-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: capi
spec:
  values: ""

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: capi-system
  labels:
    addons.in-cloud.io/values: system
    addons.in-cloud.io/addon: capi
spec:
  values: |
    certificates:
      useExternalIssuer: true
      externalIssuer:
        name: selfsigned-cluster-issuer