apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonTemplate
metadata:
  name: argocd
spec:
  template: |
    spec:
      chart: "argo-cd"
      pluginName: helm-with-values
      repoURL: "{{ .Values.companyExternalChartRegistry }}"
      version: "9.4.15-1"
      releaseName: argocd
      targetCluster: {{ "{{ .Values.spec.variables.cluster }}" }}
      targetNamespace: "{{ .Values.companyPrefix }}-argocd"
      variables:
        cluster_name: {{ "{{ .Values.spec.variables.cluster }}" }}
        dependency: "False"
      valuesSources:
        - name: parameters-client
          sourceRef:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-client
            namespace: {{ .Values.companyPrefix }}-system
          extract:
            - as: argocdServerAdminPassword
              jsonPath: .data.argocdServerAdminPassword
            - as: dataCreationTimestamp
              jsonPath: .metadata.creationTimestamp
            - as: istioGwVip
              jsonPath: .data.systemIstioGwVip
            - as: companyPrefix
              jsonPath: .data.companyPrefix
            - as: companyDomain
              jsonPath: .data.companyDomain
            - as: companyInternalGitRepository
              jsonPath: .data.companyInternalGitRepository
            - as: companyAdminUser
              jsonPath: .data.companyAdminUser
      initDependencies: []
      backend: 
        finalizer: true
        type: "argocd"
        namespace: "{{ .Values.companyPrefix }}-argocd"
        project: "default"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          managedNamespaceMetadata:
            labels:
              in-cloud.io/caBundle: approved
              in-cloud.io/clusterName: {{ "{{ .Values.spec.variables.cluster }}" }}
          syncOptions:
            - ApplyOutOfSyncOnly=true
            - CreateNamespace=true
      valuesSelectors:
        - name: default
          priority: 0
          matchLabels:
            addons.in-cloud.io/values: default
            addons.in-cloud.io/addon: argocd
        - name: custom
          priority: 90
          matchLabels:
            addons.in-cloud.io/values: {{ "{{ .Values.spec.valueLabels }}" }}
            addons.in-cloud.io/addon: argocd-client
        - name: immutable
          priority: 99
          matchLabels:
            addons.in-cloud.io/values: immutable
            addons.in-cloud.io/addon: argocd