{{- if .Values.addons.argocd.enabled }}
  {{- $clientContext := set (deepCopy .) "Values" (set (deepCopy .Values) "environment" "client") -}}

  {{- include "argocd.phase" . }}

  {{- if eq .Values.environment "infra" }}
    {{- include "argocd.phase" $clientContext }}
  {{- end }}
{{- end }}
