{{- if and .Values.monitoring.enabled (eq .Values.monitoring.type "VictoriaMetrics") }}
{{- $scrapeConfig := .Values.monitoring.serviceScrapeConfig -}}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      monitoring.in-cloud.io/service: {{ .Release.Name }}
  endpoints:
    - port: https-metrics
      path: /metrics
      scheme: HTTPS
      honorLabels: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        serverName: {{ .Release.Name }}
      {{- with $scrapeConfig.relabelConfigs }}
      relabelConfigs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $scrapeConfig.metricRelabelConfigs }}
      metricRelabelConfigs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  jobLabel: {{ .Release.Name }}
{{- end }}
