{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "vault-secret-operator.labels" . | nindent 4 }}
    controller.in-cloud.io: vault-secret-operator
    monitoring.in-cloud.io/service: {{ include "vault-secret-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}
  name: {{ include "vault-secret-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https-metrics
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: https-metrics
  selector:
    app.kubernetes.io/name: {{ include "vault-secret-operator.name" . }}
    controller.in-cloud.io: vault-secret-operator
{{- end }}
