{{- if .Values.networkPolicies.enabled }}
{{ range $proxyName, $proxyValue := .Values.proxies }}
{{- if $proxyValue.enabled }}
{{- $proxyMergedValues  := (mergeOverwrite (deepCopy $.Values.default) $proxyValue) -}}
{{- $proxyParsedName    := (include "docker-registry.registryname" $proxyName) -}}
{{- $registryName       := printf "%s-%s" (include "docker-registry.fullname" $) $proxyParsedName -}}
{{- $serviceAccountName := "default" -}}
{{- if $proxyMergedValues.serviceAccount.create }}
{{- $serviceAccountName = $registryName -}}
{{- if $proxyMergedValues.serviceAccount.name }}
{{- $serviceAccountName = $proxyMergedValues.serviceAccount.name -}}
{{- end }}
{{- end }}
{{- $config             := $proxyMergedValues.config | default dict -}}
{{- $storage            := dig "config" "storage" dict $config  -}}
{{- $storageType        := $storage.type | default "inmemory" -}}
{{- $s3Endpoint         := regexReplaceAll "https?://([^/]+).*" (dig "s3" "regionendpoint" "" $storage) "$1" -}}
{{- $proxyEndpoint      := regexReplaceAll "https?://([^/]+).*" (dig "proxy" "remoteurl" "registry-1.docker.io" $config) "$1" -}}

{{- if and (eq $storageType "s3") $s3Endpoint }}
---
# Common selector: applies to all docker-registry-cache pods (by app.kubernetes.io/name).
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "allow-egress-{{ $registryName }}-to-coredns-s3-53"
  namespace: {{ $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $serviceAccountName }}
      k8s:io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ $.Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: '53'
        protocol: UDP
      - port: '53'
        protocol: TCP
      rules:
        dns:
        - matchName: {{ $s3Endpoint }}
  description: |
    Allows egress from all {{ $registryName }} pods to CoreDNS on 53 for S3 backend name resolution.

---
# Common selector: applies to all docker-registry-cache pods (by app.kubernetes.io/name).
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "allow-egress-{{ $registryName }}-to-s3-storage-443"
  namespace: {{ $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $serviceAccountName }}
      k8s:io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
  egress:
  - toFQDNs:
    - matchName: {{ $s3Endpoint }}
    toPorts:
    - ports:
      - port: '443'
        protocol: TCP
  description: |
    Allows egress from all {{ $registryName }} pods to the S3 backend storage on 443.
{{- end }}

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "allow-ingress-{{ $registryName }}-from-vmagent-11043"
  namespace: {{ $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $serviceAccountName }}
      k8s:io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ $.Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '11043'
        protocol: TCP
  description: |
    Allows ingress from vmagent to {{ $registryName }} on 11043 for metrics collection.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "allow-egress-{{ $registryName }}-to-coredns-53"
  namespace: {{ $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $serviceAccountName }}
      k8s:io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ $.Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: '53'
        protocol: UDP
      - port: '53'
        protocol: TCP
      rules:
        dns:
        - matchName: {{ $proxyEndpoint }}
  description: |
    Allows egress from {{ $registryName }} to CoreDNS on 53 for DNS resolution.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "allow-egress-{{ $registryName }}-to-world-443"
  namespace: {{ $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $serviceAccountName }}
      k8s:io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
  egress:
  - toEntities:
    - world
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      rules:
        dns:
        - matchName: {{ $proxyEndpoint }}
  description: |
    Allows egress from {{ $registryName }} to world on 443.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "allow-egress-{{ $registryName }}-to-kube-apiserver-6443"
  namespace: {{ $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $serviceAccountName }}
      k8s:io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: |
    Allows egress from {{ $registryName }} to the Kubernetes API server on 6443.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "allow-egress-{{ $registryName }}-to-upstream-443"
  namespace: {{ $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $serviceAccountName }}
      k8s:io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
  egress:
  - toFQDNs:
    - matchName: {{ $proxyEndpoint }}
    toPorts:
    - ports:
      - port: '443'
        protocol: TCP
  description: |
    Allows egress from {{ $registryName }} to {{ $proxyEndpoint }} on 443.

---
# Allow istio gateway to reach docker registry cache on 5000.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-istio-gw-to-{{ $registryName }}-5000
  namespace: {{ $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $serviceAccountName }}
      k8s:io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: istio-gw
        k8s:io.kubernetes.pod.namespace: {{ $.Values.companyPrefix }}-istio-gw
    toPorts:
    - ports:
      - port: '5000'
        protocol: TCP
  description: |
    Allows ingress from istio-gw to {{ $registryName }} on 5000.
{{- end }}
{{- end }}
{{- end }}
