{{- if .Values.networkPolicies.repoServer.enabled }}

---
# Allow `argocd-repo-server` to talk to the Kubernetes API server (infra).
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-argocd-repo-server-to-kube-apiserver-6443
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.repoServer.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  ingress:
  - {}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from argocd-repo-server to the Kubernetes API server
    on 6443 for control-plane interactions.

---
# Allow `argocd-server` to resolve DNS via CoreDNS.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-argocd-repo-server-to-coredns-53
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.repoServer.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  ingress:
  - {}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
      rules:
        dns:
        - matchPattern: '*'
  description: Allows egress from argocd-server to CoreDNS on 53 for DNS resolution.

---
# Allow `argocd-repo-server` to redis.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-argocd-repo-server-to-redis-6379
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.repoServer.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  ingress:
  - {}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.redis.serviceAccountName" . }}
        k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
    toPorts:
    - ports:
      - port: '6379'
        protocol: TCP
  description: Allows egress from argocd-repo-server to Redis on 6379 for data storage.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-argocd-repo-server-from-argocd-application-controller-8081
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.repoServer.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  egress:
  - {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.controller.serviceAccountName" . }}
        k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
    toPorts:
    - ports:
      - port: '8081'
        protocol: TCP
  description: Allows ingress from argocd-application-controller to argocd-repo-server on 8081.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-argocd-repo-server-from-argocd-server-8081
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.repoServer.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  egress:
  - {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.server.serviceAccountName" . }}
        k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
    toPorts:
    - ports:
      - port: '8081'
        protocol: TCP
  description: Allows ingress from argocd-server to argocd-repo-server on 8081.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-argocd-repo-server-to-fqdns-443-80
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.repoServer.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  ingress:
  - {}
  egress:
  - toFQDNs:
    - matchName: github.com
    - matchName: blog.{{ .Values.companyPrefix }}.com
    - matchName: istio-release.storage.googleapis.com
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      - port: "80"
        protocol: TCP
  description: Allows egress for argocd-repo-server to specific external FQDNs on 80 and 443 for external repositories.

---
# Allow vmagent to scrape `argocd-repo-server` metrics.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-vmagent-to-argocd-repo-server-11043
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.repoServer.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '11043'
        protocol: TCP
  egress:
  - {}
  description: Allows ingress from vmagent to argocd-repo-server on 11043 for
    metrics collection.

{{- end }}
