{{- if .Values.addons.coredns.enabled }}
{{- $context  := set (deepCopy .) "Values" (set (deepCopy .Values) "addonName" "coredns") -}}

  {{- range $name := list
    "default"
    "immutable"
    "infra"
    "network-policies"
    "client"
    "initialized"
    "vm-operator"
    "system"
    "multi-control-plane"
  }}
    {{- $_        := set $context.Values "addonValueName" $name -}}
    {{- include "common.addonValue" $context }}
    {{- $.Files.Get (printf "files/coredns/%s.goyaml" $name) | nindent 4 }}
  {{- end }}

{{- end }}
