{{- range $appName, $appValue := .Values.applications }}
  {{- if $appValue.enabled }}
    {{- if and $appValue.monitoring.enabled (eq $appValue.monitoring.type "VictoriaMetrics") }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $.Release.Name }}-monitoring-client"
  namespace: {{ $.Release.Namespace }}
spec:
  commonName: metrics-reader
  duration: 8760h
  isCA: false
  issuerRef:
    kind: ClusterIssuer
    name: ca-client
  privateKey:
    algorithm: RSA
    size: 2048
  renewBefore: 1460h
  secretName: monitoring-client
  subject:
    organizations:
      - beget:metrics-reader
  usages:
  - client auth
    {{- end }}
  {{- end }}
{{- end }}
