{{- range $appName, $appValue := .Values.applications }}
  {{- if $appValue.enabled }}
    {{- if and $appValue.monitoring.enabled (eq $appValue.monitoring.type "VictoriaMetrics") }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-controller-manager-monitoring"
  namespace: {{ $.Release.Namespace }}
  labels:
    monitoring.in-cloud.io/service: "{{ $.Release.Name }}-controller-manager-monitoring"
spec:
  ports:
    - name: https-metrics
      port: {{ index $appValue.containers.kubeControllerManager.extraArgs "secure-port" | default "20257" }}
      protocol: TCP
      targetPort: {{ index $appValue.containers.kubeControllerManager.extraArgs "secure-port" | default "20257" }}
  selector:
    app.kubernetes.io/name: control-plane
  type: ClusterIP
    {{- end }}
  {{- end }}
{{- end }}
