{{- range $appName, $appValue := .Values.applications }}
  {{- if $appValue.enabled }}
    {{- if and $appValue.monitoring.enabled (eq $appValue.monitoring.type "VictoriaMetrics") }}
    {{- $defaultServerName := "client-cp-scheduler" }}
    {{- $serverName := "" }}
    {{- if $appValue.csiDriver }}
    {{- $serverName = ((dig "volumes" "scheduler-server-csi" "volume" "volumeAttributes" "csi.cert-manager.io/dns-names" $defaultServerName $appValue) | split ",")._0 }}
    {{- else }}
    {{- $serverName = ((dig "containers" "kubeScheduler" "certSANs" list $appValue) | first | default $defaultServerName) }}
    {{- end }}

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: "{{ $.Release.Name }}-scheduler"
  namespace: {{ $.Release.Namespace }}
spec:
  endpoints:
    - port: https-metrics
      scheme: "https"
      tlsConfig:
        serverName: "{{ $serverName }}"
        ca:
          secret:
            name: "{{ $.Release.Name }}-monitoring-client"
            key: ca.crt
        cert:
          secret:
            name: "{{ $.Release.Name }}-monitoring-client"
            key: tls.crt
        keySecret:
          name: "{{ $.Release.Name }}-monitoring-client"
          key: tls.key
  selector:
    matchLabels:
      monitoring.in-cloud.io/service: "{{ $.Release.Name }}-scheduler-monitoring"
  jobLabel: jobLabel
    {{- end }}
  {{- end }}
{{- end }}
