{{- if .Values.networkPolicies.enabled }}
---
# Allow `svc-hub` to resolve Consul/RabbitMQ names via CoreDNS.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-svc-hub-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "svc-hub.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: '53'
        protocol: UDP
      - port: '53'
        protocol: TCP
      rules:
        dns:
        - matchName: consul.{{ .Values.companyPrefix }}
        - matchName: consul.{{ .Values.companyPrefix }}.{{ .Values.clusterDomain }}
        - matchName: consul.{{ .Values.companyPrefix }}.svc.{{ .Values.clusterDomain }}
        - matchName: consul.{{ .Values.companyPrefix }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
        - matchName: amqp.rabbit-hub.service.consul
        - matchName: amqp.rabbit-hub.service.consul.{{ .Values.clusterDomain }}
        - matchName: amqp.rabbit-hub.service.consul.svc.{{ .Values.clusterDomain }}
        - matchName: amqp.rabbit-hub.service.consul.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
  description: Allows egress from svc-hub to CoreDNS on 53 for Consul/RabbitMQ name
    resolution.

---
# Allow kubelet to probe `svc-hub` health.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-host-probes-svc-hub-6379
  namespace: {{ .Release.Namespace }}
spec:
  description: "Allow kubelet probes to svc-hub on :6379"
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "svc-hub.serviceAccountName" . }}
  ingress:
  - fromEntities:
    - host
    toPorts:
    - ports:
      - port: "6379"
        protocol: TCP

---
# Allow `svc-hub` to reach the Consul service.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-svc-hub-to-consul-8500
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "svc-hub.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toFQDNs:
    - matchName: consul.{{ .Values.companyPrefix }}
    toPorts:
    - ports:
      - port: '8500'
        protocol: TCP
  description: Allows egress from svc-hub to the Consul service on 8500.

---
# Allow `svc-hub` to reach the RabbitMQ hub.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-svc-hub-to-rabbit-hub-5672
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "svc-hub.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toFQDNs:
    - matchName: amqp.rabbit-hub.service.consul
    toPorts:
    - ports:
      - port: '5672'
        protocol: TCP
  description: Allows egress from svc-hub to the RabbitMQ hub on 5672.

---
# Allow ingress from `svc-k8s-proxy` to `svc-hub`.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-svc-k8s-proxy-svc-hub-from-8082
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "svc-hub.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: svc-k8s-proxy
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-svc-k8s-proxy
    toPorts:
    - ports:
      - port: '8082'
        protocol: TCP
  description: Allows ingress from svc-k8s-proxy to svc-hub on 8082.
{{- end }}
