apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc-hub.fullname" . }}
  labels:
    {{ include "svc-hub.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "svc-hub.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP