---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: ccm-csrc-controller-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: ccm-csrc-controller
spec:
  values: |
    controllerManager:
      manager:
        image:
          repository: {{ .Values.companyInternalDockerRegistry }}/k8s-charts-public/charts/ccm-csr-controller
        resources:
          limits:
            cpu: 6 # In trottling case need delete limits.cpu
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 512Mi
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: ccm-csrc-controller-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: ccm-csrc-controller
spec:
  values: ""
