{{- if .Values.addons.validatingadmissionpolicies.enabled }}
---
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: validating-admission-policies-client
spec:
  targetCluster: {{ .Values.clientName }}
  {{- include "validating-admission-policies.addon-spec" . | nindent 2 }}
{{- end }}
