---
# Source: addonset/templates/addons/dex/addon.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: dex
spec:
  chart: "dex"
  pluginName: helm-with-values
  repoURL: example.com
  version: "0.23.0-1"
  targetCluster: in-cluster
  targetNamespace: "example-dex"
  variables:
    cluster_name: in-cluster
  valuesSources:
    - name: parameters
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-infra
        namespace: example-system
      extract:
        - as: dexStaticPasswordsAdmin
          jsonPath: .data.dexStaticPasswordsAdmin
        - as: clusterName
          jsonPath: .data.clusterName
        - as: systemIstioGwDomain
          jsonPath: .data.systemIstioGwDomain
        - as: systemIstioGwVip
          jsonPath: .data.systemIstioGwVip
        - as: systemIstioGwDomainInternal
          jsonPath: .data.systemIstioGwDomainInternal
        - as: systemIstioGwVipInternal
          jsonPath: .data.systemIstioGwVipInternal
        - as: companyPrefix
          jsonPath: .data.companyPrefix
        - as: companyDomain
          jsonPath: .data.companyDomain
        - as: companyAdminUser
          jsonPath: .data.companyAdminUser
  initDependencies:
    - name: cert-manager
      criteria:
        - jsonPath: $.status.conditions[?(@.type=='Ready')].status
          operator: Equal
          value: "True"
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: dex
    - name: custom
      priority: 90
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: dex
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: dex
---
# Source: addonset/templates/addons/dex/phase.client.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: dex-client
spec:
  rules:
    - name: system
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-client
            namespace: example-system
          jsonPath: $.data.systemEnabled
          operator: Equal
          value: "true"
      selector:
        name: system
        priority: 70
        matchLabels:
          addons.in-cloud.io/values: system
          addons.in-cloud.io/addon: dex
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.status.phaseValuesSelector[?(@.name=='initialized-2')]
          operator: Exists
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator-client
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 45
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: dex
    - name: istio-base
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: istio-base-client
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: istio-base-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: dex-client
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
      selector:
        name: istio-base
        priority: 35
        matchLabels:
          addons.in-cloud.io/values: istio-base
          addons.in-cloud.io/addon: dex
---
# Source: addonset/templates/addons/dex/phase.infra.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: dex
spec:
  rules:
    - name: system
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.systemEnabled
          operator: Equal
          value: "true"
      selector:
        name: system
        priority: 70
        matchLabels:
          addons.in-cloud.io/values: system
          addons.in-cloud.io/addon: dex
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.status.phaseValuesSelector[?(@.name=='initialized-2')]
          operator: Exists
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 45
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: dex
    - name: istio-base
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: istio-base
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: istio-base
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: dex
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
      selector:
        name: istio-base
        priority: 35
        matchLabels:
          addons.in-cloud.io/values: istio-base
          addons.in-cloud.io/addon: dex
---
# Source: addonset/templates/addons/dex/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: dex-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: dex
spec:
  values: |
    dex:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
---
# Source: addonset/templates/addons/dex/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: dex-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: dex
spec:
  values: |
---
# Source: addonset/templates/addons/dex/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: dex-istio-base
  labels:
    addons.in-cloud.io/values: istio-base
    addons.in-cloud.io/addon: dex
spec:
  values: |
    istio:
      virtualService:
        enabled: true
        gateways:
          - {{ .Values.companyPrefix }}-istio-gw/default
        hosts:
          - "*"
        http:
          name: dex
          route:
            host: dex
            port: 5554
      destinationRule:
        enabled: true
        host: dex
        trafficPolicy:
          tls:
            mode: SIMPLE
            insecureSkipVerify: true
---
# Source: addonset/templates/addons/dex/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: dex-vm-operator
  labels:
    addons.in-cloud.io/values: vm-operator
    addons.in-cloud.io/addon: dex
spec:
  values: |
    monitoring:
      enabled: true
