---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: trivy-operator-system
  labels:
    addons.in-cloud.io/values: system
    addons.in-cloud.io/addon: trivy-operator
spec:
  values: |
    trivy-operator:
      trivyOperator:
        scanJobNodeSelector:
          node-role.kubernetes.io/control-plane: ""
        scanJobTolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/argocd"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/crossplane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/crossplane-core"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/crossplane-prov"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/vm-stream"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/vm-data"
            operator: "Exists"
            effect: "NoSchedule"
      nodeCollector:
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/argocd"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/crossplane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/crossplane-core"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/crossplane-prov"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/vm-stream"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/vm-data"
            operator: "Exists"
            effect: "NoSchedule"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"