{{- if .Values.networkPolicies.enabled }}
---
# Allow `certificate-set` to talk to the Kubernetes API server.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-certificate-set-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: certs-controller-manager
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from certificate-set to the Kubernetes API server on
    6443 for control-plane interactions.
{{- end }}
