apiVersion: v2
name: secret-copy-operator
description: A Helm chart to distribute the project secret-copy-operator
type: application
version: 0.1.1
appVersion: "v0.0.3-64328be5"
icon: "https://example.com/icon.png"
