---
# Source: addonset/templates/vm-operator/vm-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: vm-operator
spec:
  chart: "victoria-metrics-operator"
  repoURL: "example.com"
  version: "0.52.0-3"
  pluginName: helm-with-values
  targetCluster: in-cluster
  targetNamespace: "example-vm-operator"
  variables:
    cluster_name: in-cluster
    dependency: "True"
  valuesSources:
    - name: parameters-infra
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-infra
        namespace: example-system
      extract:
        - as: companyPrefix
          jsonPath: .data.companyPrefix
        - as: companyDomain
          jsonPath: .data.companyDomain
  initDependencies:
    - name: client-cp-control-plane
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
    - name: cert-manager-csi-driver
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
    - name: addons-operator
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: true
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: vm-operator
    - name: custom
      priority: 90
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: vm-operator
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: vm-operator
---
# Source: addonset/templates/vm-operator/vm-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: vm-operator
spec:
  rules:
    - name: infra
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.environment
          operator: Equal
          value: "infra"
      selector:
        name: infra
        priority: 10
        matchLabels:
          addons.in-cloud.io/values: infra
          addons.in-cloud.io/addon: vm-operator
    - name: cert-manager
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.status.phaseValuesSelector[?(@.name=='initialized-2')]
          operator: Exists
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: cert-manager
        priority: 20
        matchLabels:
          addons.in-cloud.io/values: "cert-manager"
          addons.in-cloud.io/addon: vm-operator
---
# Source: addonset/templates/vm-operator/vm-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: vm-operator-client
spec:
  rules:
    - name: infra
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-client
            namespace: example-system
          jsonPath: $.data.environment
          operator: Equal
          value: "infra"
      selector:
        name: infra
        priority: 10
        matchLabels:
          addons.in-cloud.io/values: infra
          addons.in-cloud.io/addon: vm-operator
    - name: cert-manager
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.status.phaseValuesSelector[?(@.name=='initialized-2')]
          operator: Exists
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: cert-manager
        priority: 20
        matchLabels:
          addons.in-cloud.io/values: "cert-manager"
          addons.in-cloud.io/addon: vm-operator
---
# Source: addonset/templates/vm-operator/vm-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: vm-operator-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: vm-operator
spec:
  values: |
    companyPrefix: {{ .Values.companyPrefix }}
    victoria-metrics-operator:
      fullnameOverride: "vm-operator"
      env:
        - name: GOMAXPROCS
          value: '1'
        - name: VM_VMAGENTDEFAULT_CONFIGRELOADERMEMORY
          value: '100Mi'
        - name: VM_VMALERTMANAGER_CONFIGRELOADERMEMORY
          value: '100Mi'
        - name: VM_VMALERTDEFAULT_CONFIGRELOADERMEMORY
          value: '100Mi'
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 320Mi
      admissionWebhooks:
        enabled: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - victoria-metrics-operator
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - vmoperator-infra
              topologyKey: failure-domain.beta.kubernetes.io/region
            weight: 100
---
# Source: addonset/templates/vm-operator/vm-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: vm-operator-infra
  labels:
    addons.in-cloud.io/values: infra
    addons.in-cloud.io/addon: vm-operator
spec:
  values: |
    victoria-metrics-operator:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
    networkPolicies:
      enabled: true
    monitoring:
      enabled: true
---
# Source: addonset/templates/vm-operator/vm-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: vm-operator-client
  labels:
    addons.in-cloud.io/values: client
    addons.in-cloud.io/addon: vm-operator
spec:
  values: |
    victoria-metrics-operator:
      podLabels:
        toleration.{{ .Values.companyDomain }}/ignore: "true"
      tolerations:
        - operator: "Exists"
---
# Source: addonset/templates/vm-operator/vm-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: vm-operator-cert-manager
  labels:
    addons.in-cloud.io/values: "cert-manager"
    addons.in-cloud.io/addon: vm-operator
spec:
  values: |
    argocdPlugins:
      kustomize: true
    monitoring:
      secureService:
        enabled: true
        issuer:
          name: selfsigned-cluster-issuer
---
# Source: addonset/templates/vm-operator/vm-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: vm-operator-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: vm-operator
spec:
  values: ""
