---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: vault-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: vault
spec:
  values: ""

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: vault-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: vault
spec:
  values: ""
