---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addon-set-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: addon-set
spec:
  values: |
    addons:
      system:
        enabled: {{ Values.cluster.systemEnabled }}
    clientName: {{ .Values.cluster.client.name }}
    clusterName: {{ .Values.cluster.name }}
    addonRevision: {{ .Values.addonRevision }}
    clientClusterEnabled: {{ .Values.cluster.clusterClientEnabled }}

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addon-set-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: addon-set
spec:
  values: ""

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addon-set-infra
  labels:
    addons.in-cloud.io/values: infra
    addons.in-cloud.io/addon: addon-set
spec:
  values: |
    addons:
      clientkubestatemetrics:
        enabled: true
      clientvmscrapeconfig:
        enabled: true
