---
apiVersion: v1
kind: Service
metadata:
  name: istio-gw-internal
  labels:
    monitoring.in-cloud.io/service: istio-gw-internal
spec:
  ports:
    - name: https-metrics
      port: 11043
      protocol: TCP
      targetPort: https-metrics
