{{- if .Values.networkPolicies.enabled }}
{{- $endpoint := .Values.signalilo.config.icinga_url -}}
{{- $proto := regexFind "^https?" $endpoint -}}
{{- $host := regexReplaceAll "^https?://([^:/]+).*" $endpoint "${1}" -}}
{{- $port := regexFind ":[0-9]+$" $endpoint | trimPrefix ":" -}}
{{- if eq $port "" -}}
  {{- if eq $proto "https" -}}
    {{- $port = "443" -}}
  {{- else -}}
    {{- $port = "80" -}}
  {{- end -}}
{{- end -}}
{{- $isIP := regexMatch "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$" $host -}}

---
# Allow `signalilo` to reach the external Icinga endpoint.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-signalilo-to-thruk-{{ $port }}
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: signalilo
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  {{- if $isIP }}
  - toCIDR:
    - {{ $host }}/32
  {{- else }}
  - toFQDNs:
    - matchName: "{{ $host }}"
  {{- end }}
    toPorts:
    - ports:
      - port: "{{ $port }}"
        protocol: TCP
  description: |
    Allows egress from signalilo to the Icinga endpoint on {{ $port }}.

{{- if not $isIP }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-signalilo-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: signalilo
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
      rules:
        dns:
        - matchPattern: "*"
  description: |
    Allows egress from signalilo to CoreDNS on 53 for DNS resolution.
{{- end }}

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-signalilo-from-alertmanager-8888
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: signalilo
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmalertmanager-vm-alertmanager
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-alertmanager
    toPorts:
    - ports:
      - port: "8888"
        protocol: TCP
  description: |
    Allows ingress from alertmanager to signalilo on 8888 for webhook alerts.
{{- end }}
