{{- if .Values.networkPolicies.enabled }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-metrics-server-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: metrics-server
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: |
    Allows egress from metrics-server to the Kubernetes API server on 6443
    for control-plane interactions.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-metrics-server-to-remote-node-and-host-10250
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: metrics-server
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - remote-node
    - host
    toPorts:
    - ports:
      - port: '10250'
        protocol: TCP
  description: |
    Allows egress from metrics-server to host and remote-node endpoints
    on 10250 for kubelet scraping.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-vmagent-to-metrics-server-10250
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: metrics-server
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '10250'
        protocol: TCP
  description: |
    Allows ingress from vmagent to metrics-server on 10250 for metrics
    collection.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-kapi-and-rnode-to-metrics-server-10250
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: metrics-server
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEntities:
    - kube-apiserver
    - remote-node
    toPorts:
    - ports:
      - port: '10250'
        protocol: TCP
  description: |
    Allows ingress from kube-apiserver-and-remote-node to metrics-server
    on 10250.
{{- end }}
