{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "worker-group-claim-operator.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    name: {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "workergroupclaim-viewer-role" "context" $) }}
rules:
    - apiGroups:
        - workergroup.in-cloud.io
      resources:
        - workergroupclaims
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - workergroup.in-cloud.io
      resources:
        - workergroupclaims/status
      verbs:
        - get
{{- end }}
