---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: "{{ .Values.companyPrefix }}-cm-provider-default"
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: "{{ .Values.companyPrefix }}-cm-provider"
spec:
  values: ""

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: "{{ .Values.companyPrefix }}-cm-provider-vm-operator"
  labels:
    addons.in-cloud.io/values: vm-operator
    addons.in-cloud.io/addon: "{{ .Values.companyPrefix }}-cm-provider"
spec:
  values: |
    monitoring:
      vmServiceScrape:
        enabled: true

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: "{{ .Values.companyPrefix }}-cm-provider-immutable"
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: "{{ .Values.companyPrefix }}-cm-provider"
spec:
  values: ""

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: "{{ .Values.companyPrefix }}-cm-provider-system"
  labels:
    addons.in-cloud.io/values: system
    addons.in-cloud.io/addon: "{{ .Values.companyPrefix }}-cm-provider"
spec:
  values: |
    companyPrefix: {{ .Values.companyPrefix }}
    certificates:
      useExternalIssuer: true
      externalIssuer:
        name: selfsigned-cluster-issuer
    appSpec:
      applications:
        providerControllerManager:
          name: provider-{{ .Values.companyPrefix }}-controller-manager
          containers:
            manager:
              extraArgs:
                metrics-cert-path: "/etc/provider-{{ .Values.companyPrefix }}-controller-manager/tls"
              extraVolumeMounts:
                certificate:
                  volumeMount:
                    path: "/etc/provider-{{ .Values.companyPrefix }}-controller-manager/tls"
              image:
                repository: {{ .Values.companyInternalDockerRegistry }}/cloud/k8s/controllers/capi-provider-{{ .Values.companyPrefix }}
                pullPolicy: Always
          enabled: true
          tolerations:
          - effect: NoExecute
            operator: Exists
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          imagePullSecrets:
            - name: regcred