apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "svc-k8s-proxy.fullname" . }}-kubeconfig
  labels:
    {{- include "svc-k8s-proxy.labels" . | nindent 4 }}
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: kubernetes
        cluster:
          certificate-authority: "{{ .Values.kubeconfig.caFile }}"
          server: "{{ .Values.kubeconfig.server }}"

    users:
      - name: service-account-user
        user:
          tokenFile: "{{ .Values.kubeconfig.tokenFile }}"

    contexts:
      - name: default-context
        context:
          cluster: kubernetes
          user: service-account-user
          namespace: default

    current-context: default-context
