{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (.Values.app.name | default "etcd-backup-snapshot") }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.labels.app | default "etcd-backup-snapshot" }}
    {{- with .Values.app.labels.extra }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default false }}
{{- end }}
