apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
  name: {{ include "vault-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  namespace: {{ .Release.Namespace }}
