{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
  name: {{ include "vault-operator.resourceName" (dict "suffix" "vaultclaim-admin-role" "context" $) }}
rules:
  - apiGroups:
      - vault.in-cloud.io
    resources:
      - vaultclaims
    verbs:
      - '*'
  - apiGroups:
      - vault.in-cloud.io
    resources:
      - vaultclaims/status
    verbs:
      - get
{{- end }}
