---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: worker-group-claim-operator-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: worker-group-claim-operator
spec:
  values: |
    manager:
      image:
        repository: prorobotech/worker-group-claim-operator
        tag: main-bdb23701

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: worker-group-claim-operator-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: worker-group-claim-operator
spec:
  values: ""
