---
apiVersion: clusterclaim.in-cloud.io/v1alpha1
kind: ClusterClaimObserveResourceTemplate
metadata:
  name: {{ .Release.Name }}-certificateset-client
spec:
  apiVersion: in-cloud.io/v1alpha1
  kind: CertificateSet
  value: |
    metadata:
      annotations:
        secret-copy.in-cloud.io/dstClusterKubeconfig: {{`{{ .ClusterClaim.metadata.namespace }}`}}/{{`{{ .ClusterClaim.metadata.name }}`}}-infra-kubeconfig
        secret-copy.in-cloud.io/dstNamespace: {{ .Values.extraArgs.companyPrefix }}-system
        strategy.secret-copy.in-cloud.io/ifExist: overwrite
      labels:
        cluster.x-k8s.io/cluster-name: {{`{{ .ClusterClaim.metadata.name }}`}}-client
        clusterctl.cluster.x-k8s.io/move: "true"
        secret-copy.in-cloud.io: "true"
        xcluster.in-cloud.io/name: {{`{{ .ClusterClaim.metadata.name }}`}}
    spec:
      environment: client
      issuerRef:
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        name: selfsigned
      kubeconfig: true
      kubeconfigEndpoint: "https://{{`{{ .InfraControlPlaneEndpoint.Host }}`}}:{{`{{ .ClusterClaim.spec.client.network.kubeApiserverPort }}`}}"

