---
# Source: addonset/templates/addons/addons-operator/addon.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: addons-operator
spec:
  chart: "addon-operator"
  repoURL: "example.com"
  version: "0.1.4"
  targetCluster: in-cluster
  targetNamespace: "example-addons-operator"
  valuesSources:
    - name: parameters-infra
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-infra
        namespace: example-system
      extract:
        - as: companyPrefix
          jsonPath: .data.companyPrefix
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: addons-operator
    - name: custom
      priority: 95
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: addons-operator
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: addons-operator
---
# Source: addonset/templates/addons/addons-operator/phase.infra.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: addons-operator
spec:
  rules:
    - name: infra
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.environment
          operator: Equal
          value: "infra"
      selector:
        name: infra
        priority: 20
        matchLabels:
          addons.in-cloud.io/values: infra
          addons.in-cloud.io/addon: addons-operator
    - name: cert-manager
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.status.phaseValuesSelector[?(@.name=='initialized-2')]
          operator: Exists
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: cert-manager
        priority: 25
        matchLabels:
          addons.in-cloud.io/values: cert-manager
          addons.in-cloud.io/addon: addons-operator
    - name: network-policies
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.environment
          operator: Equal
          value: "infra"
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cilium
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cilium
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: AddonPhase
            name: extra-resources
          jsonPath: $.status.ruleStatuses[?(@.name=='network-policies-argocd')].deployed
          operator: Equal
          value: true
      selector:
        name: network-policies
        priority: 65
        matchLabels:
          addons.in-cloud.io/values: network-policies
          addons.in-cloud.io/addon: addons-operator
    - name: system
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.systemEnabled
          operator: Equal
          value: "true"
      selector:
        name: system
        priority: 70
        matchLabels:
          addons.in-cloud.io/values: system
          addons.in-cloud.io/addon: addons-operator
    - name: disable-webhook
      criteria:
        - source:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            name: addonset
            namespace: example-argocd
          jsonPath: $.status.sync.status
          operator: NotEqual
          value: Synced
          keep: false
        - source:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            name: addonset
            namespace: example-argocd
          jsonPath: $.spec.syncPolicy.automated
          operator: Exists
          keep: false
      selector:
        name: disable-webhook
        priority: 80
        matchLabels:
          addons.in-cloud.io/values: disable-webhook
          addons.in-cloud.io/addon: addons-operator
---
# Source: addonset/templates/addons/addons-operator/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: addons-operator
spec:
  values: |
    certManager:
      enable: false
    managerClaim:
      image:
        repository: prorobotech/addons-operator-addonclaim
    webhook:
      enable: false
    manager:
      env:
      - name: ENABLE_WEBHOOKS
        value: false
      image:
        repository: prorobotech/addons-operator
        pullPolicy: IfNotPresent
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
    metrics:
      enable: false
      port: 8443
---
# Source: addonset/templates/addons/addons-operator/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: addons-operator
spec:
  values: |
---
# Source: addonset/templates/addons/addons-operator/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-cert-manager
  labels:
    addons.in-cloud.io/values: cert-manager
    addons.in-cloud.io/addon: addons-operator
spec:
  values: |
    webhook:
      enable: true
    certManager:
      enable: true
    manager:
      env:
      - name: ENABLE_WEBHOOKS
        value: true
    metrics:
      enable: true
      port: 8443
---
# Source: addonset/templates/addons/addons-operator/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-infra
  labels:
    addons.in-cloud.io/values: infra
    addons.in-cloud.io/addon: addons-operator
spec:
  values: |
---
# Source: addonset/templates/addons/addons-operator/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-system
  labels:
    addons.in-cloud.io/values: system
    addons.in-cloud.io/addon: addons-operator
spec:
  values: |
    managerClaim:
      enable: true
    manager:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
---
# Source: addonset/templates/addons/addons-operator/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-network-policies
  labels:
    addons.in-cloud.io/values: network-policies
    addons.in-cloud.io/addon: addons-operator
spec:
  values: |

    companyPrefix: {{ .Values.companyPrefix }}
    networkPolicies:
      enabled: true
---
# Source: addonset/templates/addons/addons-operator/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: addons-operator-disable-webhook
  labels:
    addons.in-cloud.io/values: disable-webhook
    addons.in-cloud.io/addon: addons-operator
spec:
  values: |
    webhook:
      enable: false
