{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: certs
        control-plane: controller-manager
        monitoring.in-cloud.io/service: certs-controller-manager-metrics-service
    name: certs-controller-manager-metrics-service
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - name: https-metrics
          port: {{ .Values.metrics.port }}
          protocol: TCP
          targetPort: https-metrics
    selector:
        app.kubernetes.io/name: certs
        control-plane: controller-manager
{{- end }}
