victoria-metrics-k8s-stack:
  fullnameOverride: ""
  nameOverride: ""

  alertmanager:
    enabled: false
    config:
      global:
        resolve_timeout: 5m

      route:
        receiver: blackhole
        group_by: ["cluster_full_name", "alertname", "severity"]
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 3h

        routes:
          - matchers:
              - alertname="Watchdog"
            receiver: blackhole
          - matchers:
              - severity="critical"
            receiver: telegram-critical
            continue: true
          - matchers:
              - severity="critical"
            receiver: signalilo-critical
            continue: true

      receivers:
        - name: blackhole
        - name: telegram-critical
          telegram_configs:
            - bot_token: "123456789:AAExampleTokenHere"
              chat_id: -1001234567890
              parse_mode: 'HTML'
              send_resolved: true
              message: '{{ template "tg.message" . }}'
        - name: signalilo-critical
          webhook_configs:
            - url: "http://signalilo.beget-signalilo.svc/webhook?token=HrVSzDOrZthErVJwxddMJHefHYkvr/XWVc1XGcazh1I="
              send_resolved: true

  vmagent:
    enabled: false

  vmalert:
    enabled: false

  clickhouseIserter:
    enabled: false

  vmcluster:
    enabled: false

monitoring:
  enabled: false
  type: VictoriaMetrics
  namespace: default
  secureService:
    enabled: false
    # Create a secret containing both 'tls.crt' and 'tls.key' fields
    issuer:
      kind: ClusterIssuer
      name: default
  grafana:
    vmDatasource:
      enabled: false

additionalService:
  vmcluster:
    enabled: false

tls:
  vmInsert:
    enabled: false
    issuer:
      kind: ClusterIssuer
      name: default-issuer-name
    certificate:
      name: vminsert-tls
      secretName: vminsert-tls
      duration: 8760h
      renewBefore: 720h
      commonName: vminsert
      dnsNames:
        - vminsert.default.svc
        - vminsert.default.svc.cluster.local
      ipAddresses:
        - "127.0.0.1"

  vmSelect:
    enabled: false
    issuer:
      kind: ClusterIssuer
      name: default-issuer-name
    certificate:
      name: vmselect-tls
      secretName: vmselect-tls
      duration: 8760h
      renewBefore: 720h
      commonName: vmselect
      dnsNames:
        - vmselect.default.svc
        - vmselect.default.svc.cluster.local
      ipAddresses:
        - "127.0.0.1"

istioVirtualService:
  vmalert:
    enabled: false
    gateways:
      - beget-istio-gw/default
    hosts:
      - "*"
    path: "/vmalert"
    http:
      name: vmalert
      route:
        host: vmalert
        port: 8080

  alertmanager:
    enabled: false
    issuer:
      kind: ClusterIssuer
      name: default-issuer-name
    certificate:
      name: alertmanager-tls
      secretName: alertmanager-tls
      duration: 8760h
      renewBefore: 720h
      commonName: alertmanager
      dnsNames:
        - alertmanager.default.svc
        - alertmanager.default.svc.cluster.local
      ipAddresses:
        - "127.0.0.1"
