---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: signalilo-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: signalilo
spec:
  values: |
    signalilo:
      fullnameOverride: "signalilo"
      config:
        uuid: {{ .Variables.uuid }}
        icinga_hostname: {{ .Variables.icingaHostname }}
        icinga_url: {{ .Variables.icingaUrl }}
        icinga_username: {{ .Variables.icingaUsername }}
        icinga_password: {{ .Variables.icingaPassword }}
        alertmanager_port: {{ .Variables.alertmanagerSignaliloPort }}
        alertmanager_bearer_token: {{ .Variables.alertmanagerSignaliloToken }}
      extraEnvVars:
        - name: SIGNALILO_LOG_LEVEL
          value: "2"
        - name: SIGNALILO_ICINGA_INSECURE_TLS
          value: "true"
        - name: SIGNALILO_ICINGA_DEBUG
          value: "false"
        - name: SIGNALILO_ALERTMANAGER_PLUGINOUTPUT_ANNOTATIONS
          value: "message\nsummary\ndescription"
        - name: SIGNALILO_ALERTMANAGER_PLUGINOUTPUT_BY_STATES
          value: "true"
        - name: SIGNALILO_ICINGA_SERVICE_TEMPLATE
          value: "signalilo-passive-service"
        - name: SIGNALILO_ICINGA_KEEP_FOR
          value: "2h"
        - name: SIGNALILO_ICINGA_GC_INTERVAL
          value: "15m"
        - name: "SIGNALILO_ICINGA_DISPLAY_NAME_AS_SERVICE_NAME"
          value: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: signalilo-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: signalilo
spec:
  values: ""
