{{- if .Values.networkPolicies.enabled }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-incloud-web-chart-oauth2-proxy-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-oauth2-proxy
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: |
    Allows egress from incloud-web-chart-oauth2-proxy to the Kubernetes API server on 6443
    for control-plane interactions.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-incloud-web-chart-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-incloud-web-chart
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: |
    Allows egress from incloud-web-chart to the Kubernetes API server on 6443
    for control-plane interactions.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-incloud-web-chart-oauth2-proxy-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-oauth2-proxy
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
      rules:
        dns:
        - matchPattern: "*"
  description: |
    Allows egress from incloud-web-chart-oauth2-proxy to coredns on 53. Ingress remains
    open in this policy.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-incloud-web-chart-oauth2-proxy-to-dex-fqdn
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-oauth2-proxy
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
    - toFQDNs:
        - matchName: {{ .Values.systemDomain }}
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-incloud-web-chart-to-oauth2-proxy-4180
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-incloud-web-chart
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-oauth2-proxy
        k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
    toPorts:
    - ports:
      - port: '4180'
        protocol: TCP
  description: |
    Allows egress from incloud-web-chart to incloud-web-chart-oauth2-proxy on 4180 for OAuth2 proxy functionality.
    open in this policy.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-incloud-web-chart-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-incloud-web-chart
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: '53'
        protocol: UDP
      - port: '53'
        protocol: TCP
  description: |
    Allows egress from incloud-web-chart to coredns on 53 for DNS resolution.
    open in this policy.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-incloud-web-chart-from-oauth2-proxy
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-incloud-web-chart
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-oauth2-proxy
        k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
    toPorts:
    - ports:
      - port: '8081'
        protocol: TCP
  description: |
    Allows ingress to incloud-web-chart from oauth2-proxy on 8081.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-vmagent-to-incloud-web-chart-11043
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-oauth2-proxy
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '11043'
        protocol: TCP
  description: |
    Allows ingress from vmagent to incloud-web-chart on 11043 for metrics collection.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-istio-gw-to-incloud-web-chart-oauth2-proxy-4180
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-oauth2-proxy
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: istio-gw
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-istio-gw
    toPorts:
    - ports:
      - port: '4180'
        protocol: TCP
  description: |
    Allows ingress from istio-gw to incloud-web-chart-oauth2-proxy on 4180 for OAuth2 proxy functionality.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-incloud-web-chart-to-incloud-web-chart-oauth2-proxy-4180
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-oauth2-proxy
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-incloud-web-chart
        k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
    toPorts:
    - ports:
      - port: '4180'
        protocol: TCP
  description: |
    Allows ingress from incloud-web-chart to incloud-web-chart-oauth2-proxy on 4180 for OAuth2 proxy functionality.
{{- end }}
