apiVersion: v2
name: gateway
description: Helm chart for deploying Istio gateways
type: application

sources:
- https://github.com/istio/istio
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways

<<<<<<< HEAD
version: 1.26.0-7
=======
version: 1.26.0-6
>>>>>>> 9b32263b (feature(K8S-237): update charts)

appVersion: "1.26.0"

dependencies:
  - name: gateway
    version: "1.26.0"
    repository: "https://istio-release.storage.googleapis.com/charts"
