companyPrefix: example

gateway: {}

networkPolicies:
  enabled: false
  internal:
    enabled: false

monitoring:
  serviceScrapeConfig:
    metricRelabelConfigs:
      - sourceLabels: [__name__]
        action: keep
        regex: |
          container_cpu_cfs_periods_total|
          container_cpu_cfs_throttled_periods_total|
          container_cpu_cfs_throttled_seconds_total|
          container_cpu_usage_seconds_total|
          container_memory_rss|
          container_memory_working_set_bytes|
          container_network_receive_bytes_total|
          container_network_receive_errors_total|
          container_network_receive_packets_dropped_total|
          container_network_receive_packets_total|
          container_network_transmit_bytes_total|
          container_network_transmit_errors_total|
          container_network_transmit_packets_dropped_total|
          container_network_transmit_packets_total|
          container_oom_events_total|
          kube_service_info|
          namespace_cpu|
          namespace_memory|
          node_namespace_pod:kube_pod_info:|
          scrape_series_added|
          up
  enabled: false
  type: VictoriaMetrics
  namespace: default
  secureService:
    enabled: false
    # Create a secret containing both 'tls.crt' and 'tls.key' fields
    issuer:
      kind: ClusterIssuer
      name: default

tls:
  enabled: false
  issuer:
    kind: ClusterIssuer
    name: default-issuer-name
  certificate:
    name: gateway-tls
    secretName: gateway-tls
    duration: 8760h
    renewBefore: 720h
    commonName: gateway
    dnsNames:
      - gateway.default.svc
      - gateway.default.svc.cluster.local
    ipAddresses:
      - "127.0.0.1"

extraGateway:
  enabled: false
  name: default
  servers:
    - hosts: ["*"]
      port:
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: default-secret
    - hosts: ["*"]
      port:
        protocol: HTTP 

telemetry:
  enabled: false