kube-state-metrics:
  enabled: true
  # some values for kube-state-metrics

companyPrefix: example

monitoring:
  enabled: false
  type: VictoriaMetrics
  namespace: default
  secureService:
    enabled: false
    # Create a secret containing both 'tls.crt' and 'tls.key' fields
    issuer:
      kind: ClusterIssuer
      name: default
  serviceScrapeConfig:
    relabelConfigs: []
    metricRelabelConfigs:
      - sourceLabels: [__name__]
        action: keep
        regex: |
          in_cloud_capi_cluster_condition|
          in_cloud_capi_cluster_controlplane_available_replicas|
          in_cloud_capi_cluster_controlplane_desired_replicas|
          in_cloud_capi_cluster_controlplane_ready_replicas|
          in_cloud_capi_cluster_controlplane_replicas|
          in_cloud_capi_cluster_controlplane_uptodate_replicas|
          in_cloud_capi_cluster_created_timestamp_seconds|
          in_cloud_capi_cluster_deleted_timestamp_seconds|
          in_cloud_capi_cluster_resource_info|
          in_cloud_capi_cluster_spec_paused|
          in_cloud_capi_cluster_status_phase|
          in_cloud_capi_cluster_workers_available_replicas|
          in_cloud_capi_cluster_workers_desired_replicas|
          in_cloud_capi_cluster_workers_ready_replicas|
          in_cloud_capi_cluster_workers_replicas|
          in_cloud_capi_cluster_workers_uptodate_replicas|
          in_cloud_capi_clusterclaim_client_cluster_info|
          in_cloud_capi_clusterclaim_client_clusterclaim_deleted_timestamp_seconds|
          in_cloud_capi_clusterclaim_client_ready_timestamp|
          in_cloud_capi_clusterclaim_condition|
          in_cloud_capi_clusterclaim_created_timestamp_seconds|
          in_cloud_capi_clusterclaim_infra_cluster_info|
          in_cloud_capi_clusterclaim_infra_clusterclaim_deleted_timestamp_seconds|
          in_cloud_capi_clusterclaim_infra_condition|
          in_cloud_capi_clusterclaim_infra_ready_timestamp|
          in_cloud_capi_clusterclaim_resource_info|
          in_cloud_capi_clusterclaim_status_phase|
          kube_configmap_info|
          kube_daemonset_status_current_number_scheduled|
          kube_daemonset_status_desired_number_scheduled|
          kube_daemonset_status_number_available|
          kube_daemonset_status_number_misscheduled|
          kube_daemonset_status_updated_number_scheduled|
          kube_deployment_metadata_generation|
          kube_deployment_spec_replicas|
          kube_deployment_status_condition|
          kube_deployment_status_observed_generation|
          kube_deployment_status_replicas_available|
          kube_deployment_status_replicas_unavailable|
          kube_deployment_status_replicas_updated|
          kube_endpoint_info|
          kube_horizontalpodautoscaler_spec_max_replicas|
          kube_horizontalpodautoscaler_spec_min_replicas|
          kube_horizontalpodautoscaler_status_current_replicas|
          kube_horizontalpodautoscaler_status_desired_replicas|
          kube_job_status_active|
          kube_job_status_start_time|
          kube_namespace_created|
          kube_node_info|
          kube_node_labels|
          kube_node_role|
          kube_node_spec_taint|
          kube_node_spec_unschedulable|
          kube_node_status_allocatable|
          kube_node_status_capacity|
          kube_node_status_condition|
          kube_pod_container_info|
          kube_pod_container_resource_limits|
          kube_pod_container_resource_requests|
          kube_pod_container_status_last_terminated_exitcode|
          kube_pod_container_status_last_terminated_reason|
          kube_pod_container_status_ready|
          kube_pod_container_status_restarts_total|
          kube_pod_container_status_running|
          kube_pod_container_status_terminated|
          kube_pod_container_status_waiting|
          kube_pod_container_status_waiting_reason|
          kube_pod_info|
          kube_pod_owner|
          kube_pod_status_phase|
          kube_pod_status_qos_class|
          kube_pod_status_reason|
          kube_poddisruptionbudget_status_current_healthy|
          kube_poddisruptionbudget_status_desired_healthy|
          kube_secret_info|
          kube_service_info|
          kube_statefulset_metadata_generation|
          kube_statefulset_replicas|
          kube_statefulset_status_current_revision|
          kube_statefulset_status_observed_generation|
          kube_statefulset_status_replicas_ready|
          kube_statefulset_status_replicas_updated|
          kube_statefulset_status_update_revision|
          scrape_series_added|
          up

networkPolicies:
  kubeStateMetrics:
    enabled: false
  clientKubeStateMetrics:
    enabled: false