kube-state-metrics:
  enabled: true
  # some values for kube-state-metrics

companyPrefix: example

monitoring:
  enabled: false
  type: VictoriaMetrics
  namespace: default
  secureService:
    enabled: false
    # Create a secret containing both 'tls.crt' and 'tls.key' fields
    issuer:
      kind: ClusterIssuer
      name: default
  serviceScrapeConfig:
    relabelConfigs: []
    metricRelabelConfigs: []

networkPolicies:
  kubeStateMetrics:
    enabled: false
  clientKubeStateMetrics:
    enabled: false