---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: client-vm-scrape-config-initialized
  labels:
    addons.in-cloud.io/values: initialized
    addons.in-cloud.io/addon: client-vm-scrape-config
spec:
  values: |
    resources: {}

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: client-vm-scrape-config
  labels:
    addons.in-cloud.io/values: infra
    addons.in-cloud.io/addon: client-vm-scrape-config
spec:
  values: |
    resources:
      monitoringVmAgentCertificate:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: monitoring-client
          namespace: beget-vmagent
        spec:
          commonName: metrics-reader
          duration: 8760h
          isCA: false
          issuerRef:
            kind: ClusterIssuer
            name: ca-client
          privateKey:
            algorithm: RSA
            size: 2048
          renewBefore: 1460h
          secretName: monitoring-client
          subject:
            organizations:
              - beget:metrics-reader
          usages:
          - client auth

      # cadvisor metrics: /api/v1/nodes/$1/proxy/metrics/cadvisor
      # Use for calculate metrics:
      # - beget_nodegroup_memory_used_mb
      # - beget_node_memory_used_mb
      # - beget_nodegroup_filesystem_used_mb
      # - beget_nodegroup_filesystem_used_percent
      # - beget_node_filesystem_used_mb
      # - beget_node_filesystem_used_percent
      # - beget_pod_memory_usage_mb
      # - beget_pod_cpu_usage_cores
      clientClusterKubeletCadvisor:
        apiVersion: operator.victoriametrics.com/v1beta1
        kind: VMScrapeConfig
        metadata:
          name: client-cluster-kubelet-cadvisor
          namespace: beget-vmagent
        spec:
          scheme: https
          scrape_interval: 30s
          scrapeTimeout: 10s

          tlsConfig:
            ca:
              secret:
                name: monitoring-client
                key: ca.crt
            cert:
              secret:
                name: monitoring-client
                key: tls.crt
            keySecret:
              name: monitoring-client
              key: tls.key

          kubernetesSDConfigs:
            - role: node
              apiServer: "https://{{ .Values.cluster.host }}:{{ .Values.cluster.port }}"
              tlsConfig:
                ca:
                  secret:
                    name: monitoring-client
                    key: ca.crt
                cert:
                  secret:
                    name: monitoring-client
                    key: tls.crt
                keySecret:
                  name: monitoring-client
                  key: tls.key

          relabelConfigs:
            - targetLabel: __address__
              replacement: "{{ .Values.cluster.host }}:{{ .Values.cluster.port }}"
            - sourceLabels: [__meta_kubernetes_node_name]
              targetLabel: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor

            - sourceLabels: [__meta_kubernetes_node_name]
              targetLabel: node
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)

            - targetLabel: job
              replacement: kubelet-cadvisor
            - targetLabel: cluster_full_name
              replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
            - targetLabel: remotewrite_cluster
              replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
            - targetLabel: client_cluster
              replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
            - targetLabel: cluster_type
              replacement: client

      # resource metrics: /api/v1/nodes/$1/proxy/metrics/resource
      # Use for calculate metrics:
      # - beget_nodegroup_cpu_used_cores
      # -beget_node_cpu_used_cores
      clientClusterKubeletResource:
        apiVersion: operator.victoriametrics.com/v1beta1
        kind: VMScrapeConfig
        metadata:
          name: client-cluster-kubelet-resource
          namespace: beget-vmagent
        spec:
          scheme: https
          scrape_interval: 30s
          scrapeTimeout: 10s

          tlsConfig:
            ca:
              secret:
                name: monitoring-client
                key: ca.crt
            cert:
              secret:
                name: monitoring-client
                key: tls.crt
            keySecret:
              name: monitoring-client
              key: tls.key

          kubernetesSDConfigs:
            - role: node
              apiServer: "https://{{ .Values.cluster.host }}:{{ .Values.cluster.port }}"
              tlsConfig:
                ca:
                  secret:
                    name: monitoring-client
                    key: ca.crt
                cert:
                  secret:
                    name: monitoring-client
                    key: tls.crt
                keySecret:
                  name: monitoring-client
                  key: tls.key

          relabelConfigs:
            - targetLabel: __address__
              replacement: "{{ .Values.cluster.host }}:{{ .Values.cluster.port }}"
            - sourceLabels: [__meta_kubernetes_node_name]
              targetLabel: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/resource

            - sourceLabels: [__meta_kubernetes_node_name]
              targetLabel: node
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)

            - targetLabel: job
              replacement: kubelet-resource
            - targetLabel: cluster_full_name
              replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
            - targetLabel: remotewrite_cluster
              replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
            - targetLabel: client_cluster
              replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
            - targetLabel: cluster_type
              replacement: client

      # Scrape-config for api-server grafana-dashboards
      clientClusterKubeApiserver:
        apiVersion: operator.victoriametrics.com/v1beta1
        kind: VMScrapeConfig
        metadata:
          name: client-cluster-kube-apiserver
          namespace: beget-vmagent
        spec:
          scheme: https
          scrape_interval: 30s
          scrapeTimeout: 10s
          path: /metrics

          staticConfigs:
            - targets:
                - {{ .Values.cluster.host }}:{{ .Values.cluster.port }}
              labels:
                job: kube-apiserver
                cluster_full_name: {{ .Values.cluster.name }}
                remotewrite_cluster: {{ .Values.cluster.name }}
                client_cluster: {{ .Values.cluster.name }}

          tlsConfig:
            ca:
              secret:
                name: monitoring-client
                key: ca.crt
            cert:
              secret:
                name: monitoring-client
                key: tls.crt
            keySecret:
              name: monitoring-client
              key: tls.key
            insecureSkipVerify: false

          relabelConfigs:
            - targetLabel: instance
              replacement: external-apiserver
            - targetLabel: cluster_full_name
              replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
            - targetLabel: remotewrite_cluster
              replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
            - targetLabel: client_cluster
              replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
            - targetLabel: cluster_type
              replacement: client
