companyPrefix: example

victoria-metrics-operator: {}

networkPolicies:
  enabled: false

monitoring:
  enabled: false
  type: VictoriaMetrics
  secureService:
    enabled: false
    # Create a secret containing both 'tls.crt' and 'tls.key' fields
    issuer:
      kind: ClusterIssuer
      name: default
