apiVersion: v2
name: cluster-claim-operator
description: A Helm chart to distribute the project cluster-claim-operator
type: application
version: 0.1.6
appVersion: "v0.0.7-fa8ac570"
icon: "https://example.com/icon.png"
