apiVersion: v2
name: cluster-claim-operator
description: A Helm chart to distribute the project cluster-claim-operator
type: application
version: 0.1.3
appVersion: "v0.0.5-7d93653d"
icon: "https://example.com/icon.png"
