apiVersion: v2
name: cluster-claim-operator
description: A Helm chart to distribute the project cluster-claim-operator
type: application
version: 0.1.5-test-cilium
appVersion: "K8S-597-8dd771d7"
icon: "https://example.com/icon.png"
