{{- if .Values.addons.prometheusprocessexporter.enabled }}
  {{- $clientContext := set (deepCopy .) "Values" (set (deepCopy .Values) "environment" "client") -}}

  {{- include "prometheus-process-exporter.addon" . }}

  {{- .Files.Get "files/addonsMonitoring/prometheus-process-exporter/values.yml" | nindent 0 }}

  {{- include "prometheus-process-exporter.phase" . }}

  {{- if eq .Values.environment "infra" }}
    {{- include "prometheus-process-exporter.phase" $clientContext }}
  {{- end }}
{{- end }}