apiVersion: v2
name: worker-group-claim-operator
description: A Helm chart to distribute the project worker-group-claim-operator
type: application
version: 0.1.5
appVersion: "nodelabel-controller-52b3d7df"
icon: "https://example.com/icon.png"
