apiVersion: v2
name: worker-group-claim-operator
description: A Helm chart to distribute the project worker-group-claim-operator
type: application
version: 0.1.1
appVersion: "v0.0.1-bdb23701"
icon: "https://example.com/icon.png"
