---
# Source: addonset/templates/addons/client-kube-state-metrics/addon.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: client-kube-state-metrics
spec:
  chart: "kube-state-metrics"
  repoURL: "example.com"
  version: "6.1.0-5"
  pluginName: helm-with-values
  targetCluster: in-cluster
  targetNamespace: "example-client-kube-state-metrics"
  variables:
    cluster_name: in-cluster
    dependency: "True"
  valuesSources:
    - name: parameters-client
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-client
        namespace: example-system
      extract:
        - as: cluster.name
          jsonPath: .data.clusterName
        - as: cluster.customer
          jsonPath: .data.customer
        - as: companyPrefix
          jsonPath: .data.companyPrefix
        - as: companyDomain
          jsonPath: .data.companyDomain
  initDependencies:
    - name: addons-operator
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: true
    - name: addonset
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: true
    - name: client-cp-control-plane
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
    - name: client-vm-scrape-config
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
    - name: cert-manager
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: client-kube-state-metrics
    - name: custom
      priority: 95
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: client-kube-state-metrics
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: client-kube-state-metrics
---
# Source: addonset/templates/addons/client-kube-state-metrics/phase.client.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: client-kube-state-metrics-client
spec:
  rules:
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.status.phaseValuesSelector[?(@.name=='initialized-2')]
          operator: Exists
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator-client
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 45
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: client-kube-state-metrics
---
# Source: addonset/templates/addons/client-kube-state-metrics/phase.infra.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: client-kube-state-metrics
spec:
  rules:
    - name: infra
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.environment
          operator: Equal
          value: "infra"
      selector:
        name: infra
        priority: 20
        matchLabels:
          addons.in-cloud.io/values: infra
          addons.in-cloud.io/addon: client-kube-state-metrics
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.status.phaseValuesSelector[?(@.name=='initialized-2')]
          operator: Exists
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 45
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: client-kube-state-metrics
    - name: network-policies
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.environment
          operator: Equal
          value: "infra"
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cilium
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cilium
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: AddonPhase
            name: extra-resources
          jsonPath: $.status.ruleStatuses[?(@.name=='network-policies-argocd')].deployed
          operator: Equal
          value: true
      selector:
        name: network-policies
        priority: 65
        matchLabels:
          addons.in-cloud.io/values: network-policies
          addons.in-cloud.io/addon: client-kube-state-metrics
---
# Source: addonset/templates/addons/client-kube-state-metrics/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: client-kube-state-metrics-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: client-kube-state-metrics
spec:
  values: |
    kube-state-metrics:
      enabled: false
      nameOverride: client-kube-state-metrics
      tolerations:
        - operator: "Exists"
      prometheusScrape: false
      metricLabelsAllowlist:
        - nodes=[node-group.{{ .Values.companyDomain }}/name]
      customLabels:
        in-cloud.io/clusterName: ""

      collectors:
        - nodes

      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi

      extraArgs:
        - --kubeconfig=/kubeconfig/config

      volumeMounts:
       - mountPath: /kubeconfig/config
         name: kubeconfig
         subPath: config
       - mountPath: /kubeconfig/ca.crt
         name: kubeconfig-certs
         subPath: ca.crt
       - mountPath: /kubeconfig/tls.crt
         name: kubeconfig-certs
         subPath: tls.crt
       - mountPath: /kubeconfig/tls.key
         name: kubeconfig-certs
         subPath: tls.key

      volumes:
        - name: kubeconfig
          secret:
           secretName: client-kube-state-metrics-kubeconfig
        - name: kubeconfig-certs
          secret:
           secretName: monitoring-client

      kubeRBACProxy:
        enabled: true
        image:
          # registry: quay.io
          # repository: brancz/kube-rbac-proxy
          tag: v0.21.0

        extraArgs:
          - --v=2

        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"

      extraManifests:
        - apiVersion: v1
          kind: Secret
          metadata:
            name: client-kube-state-metrics-kubeconfig
            namespace: {{ .Values.companyPrefix }}-client-kube-state-metrics
          type: Opaque
          stringData:
            config: |
              apiVersion: v1
              kind: Config
              clusters:
                - name: kubernetes
                  cluster:
                    certificate-authority: /kubeconfig/ca.crt
                    server: "https://client-cp-control-plane-control-plane.{{ .Values.companyPrefix }}-system.svc:26443"
              users:
                - name: user
                  user:
                    client-certificate: /kubeconfig/tls.crt
                    client-key: /kubeconfig/tls.key
              contexts:
                - name: default-context
                  context:
                    cluster: kubernetes
                    user: user
                    namespace: default
              current-context: default-context

        - apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: monitoring-client
            namespace: {{ .Values.companyPrefix }}-client-kube-state-metrics
          spec:
            commonName: metrics-reader
            duration: 8760h
            isCA: false
            issuerRef:
              kind: ClusterIssuer
              name: ca-client
            privateKey:
              algorithm: RSA
              size: 2048
            renewBefore: 1460h
            secretName: monitoring-client
            subject:
              organizations:
                - {{ .Values.companyPrefix }}:metrics-reader
            usages:
            - client auth
---
# Source: addonset/templates/addons/client-kube-state-metrics/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: client-kube-state-metrics-infra
  labels:
    addons.in-cloud.io/values: infra
    addons.in-cloud.io/addon: client-kube-state-metrics
spec:
  values: |
    kube-state-metrics:
      enabled: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
---
# Source: addonset/templates/addons/client-kube-state-metrics/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: client-kube-state-metrics-network-policies
  labels:
    addons.in-cloud.io/values: network-policies
    addons.in-cloud.io/addon: client-kube-state-metrics
spec:
  values: |
    companyPrefix: {{ .Values.companyPrefix }}
    networkPolicies:
      clientKubeStateMetrics:
        enabled: true
---
# Source: addonset/templates/addons/client-kube-state-metrics/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: client-kube-state-metrics-vm-operator
  labels:
    addons.in-cloud.io/values: vm-operator
    addons.in-cloud.io/addon: client-kube-state-metrics
spec:
  values: |
    kube-state-metrics:
      volumes:
        - name: kubeconfig
          secret:
           secretName: client-kube-state-metrics-kubeconfig
        - name: kubeconfig-certs
          secret:
           secretName: monitoring-client
        - name: rbac-proxy-tls
          secret:
            defaultMode: 420
            secretName: client-kube-state-metrics-svc-tls

      kubeRBACProxy:
        extraArgs:
          - --tls-cert-file=/app/config/metrics/tls/tls.crt
          - --tls-private-key-file=/app/config/metrics/tls/tls.key
          - --v=2

        volumeMounts:
          - name: rbac-proxy-tls
            mountPath: /app/config/metrics/tls
            readOnly: true

    monitoring:
      enabled: true
      secureService:
        enabled: true
        issuer:
          name: selfsigned-cluster-issuer
      serviceScrapeConfig:
        relabelConfigs:
          - targetLabel: cluster_full_name
            replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
          - targetLabel: remotewrite_cluster
            replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
          - targetLabel: client_cluster
            replacement: {{ .Values.cluster.customer }}-{{ .Values.cluster.name }}
          - targetLabel: cluster_type
            replacement: client
