apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "s3-bucket-operator.labels" . | nindent 4 }}
  name: {{ include "s3-bucket-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  namespace: {{ .Release.Namespace }}
