apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "s3-bucket-operator.labels" . | nindent 4 }}
  name: {{ include "s3-bucket-operator.resourceName" (dict "suffix" "leader-election-rolebinding" "context" $) }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "s3-bucket-operator.resourceName" (dict "suffix" "leader-election-role" "context" $) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "s3-bucket-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
    namespace: {{ .Release.Namespace }}
