{{- if .Values.metrics.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "s3-bucket-operator.labels" . | nindent 4 }}
  name: {{ include "s3-bucket-operator.resourceName" (dict "suffix" "kube-rbac-proxy" "context" $) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-rbac-proxy-tokenreview
subjects:
  - kind: ServiceAccount
    name: {{ include "s3-bucket-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
    namespace: {{ .Release.Namespace }}
{{- end }}
