cilium: {}
# some values for cilium

companyPrefix: example

monitoring:
  serviceScrapeConfig:
    metricRelabelConfigs:
      - sourceLabels: [__name__]
        action: keep
        regex: |
          cilium_agent_api_process_time_seconds_count|
          cilium_agent_api_process_time_seconds_sum|
          cilium_bpf_map_ops_total|
          cilium_bpf_map_pressure|
          cilium_bpf_maps_virtual_memory_max_bytes|
          cilium_bpf_progs_virtual_memory_max_bytes|
          cilium_controllers_failing|
          cilium_controllers_runs_duration_seconds_count|
          cilium_controllers_runs_duration_seconds_sum|
          cilium_controllers_runs_total|
          cilium_datapath_conntrack_dump_resets_total|
          cilium_datapath_conntrack_gc_entries|
          cilium_drop_bytes_total|
          cilium_drop_count_total|
          cilium_endpoint_regeneration_time_stats_seconds_bucket|
          cilium_endpoint_regenerations_total|
          cilium_endpoint_state|
          cilium_errors_warnings_total|
          cilium_forward_bytes_total|
          cilium_forward_count_total|
          cilium_ip_addresses|
          cilium_k8s_client_api_calls_total|
          cilium_k8s_client_api_latency_time_seconds_count|
          cilium_kubernetes_events_received_total|
          cilium_kubernetes_events_total|
          cilium_nodes_all_events_received_total|
          cilium_nodes_all_num|
          cilium_policy|
          cilium_policy_change_total|
          cilium_policy_endpoint_enforcement_status|
          cilium_policy_l7_total|
          cilium_policy_max_revision|
          cilium_process_cpu_seconds_total|
          cilium_process_open_fds|
          cilium_process_resident_memory_bytes|
          cilium_process_virtual_memory_bytes|
          cilium_proxy_redirects|
          cilium_proxy_upstream_reply_seconds_count|
          cilium_proxy_upstream_reply_seconds_sum|
          cilium_unreachable_health_endpoints|
          cilium_unreachable_nodes|
          container_cpu_cfs_periods_total|
          container_cpu_cfs_throttled_periods_total|
          container_cpu_cfs_throttled_seconds_total|
          container_cpu_usage_seconds_total|
          container_memory_rss|
          container_memory_working_set_bytes|
          container_network_receive_bytes_total|
          container_network_receive_errors_total|
          container_network_receive_packets_dropped_total|
          container_network_receive_packets_total|
          container_network_transmit_bytes_total|
          container_network_transmit_errors_total|
          container_network_transmit_packets_dropped_total|
          container_network_transmit_packets_total|
          container_oom_events_total|
          go_gc_duration_seconds_count|
          go_gc_duration_seconds_sum|
          go_goroutines|
          go_memstats_alloc_bytes_total|
          go_memstats_gc_sys_bytes|
          go_memstats_heap_idle_bytes|
          go_memstats_heap_inuse_bytes|
          go_memstats_heap_released_bytes|
          go_memstats_mcache_sys_bytes|
          go_memstats_mspan_sys_bytes|
          go_memstats_other_sys_bytes|
          go_memstats_stack_inuse_bytes|
          go_memstats_sys_bytes|
          go_sched_latencies_seconds_bucket|
          kube_service_info|
          leader_election_master_status|
          namespace_cpu|
          namespace_memory|
          node_namespace_pod:kube_pod_info:|
          process_cpu_seconds_total|
          process_max_fds|
          process_open_fds|
          process_resident_memory_bytes|
          process_start_time_seconds|
          process_virtual_memory_bytes|
          rest_client_requests_total|
          scrape_series_added|
          up|
          workqueue_adds_total|
          workqueue_depth|
          workqueue_longest_running_processor_seconds|
          workqueue_queue_duration_seconds_count|
          workqueue_queue_duration_seconds_sum|
          workqueue_retries_total|
          workqueue_unfinished_work_seconds|
          workqueue_work_duration_seconds_count|
          workqueue_work_duration_seconds_sum
  enabled: false
  type: VictoriaMetrics
  namespace: default
  secureService:
    enabled: false
    # Create a secret containing both 'tls.crt' and 'tls.key' fields
    issuer:
      kind: ClusterIssuer
      name: default

networkPolicies:
  enabled: false