composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    common:
      targetRevision: v0.0.5

    # feature/signalilo
    crossplanecompositions:
      targetRevision: feature/signalilo
    signalilo:
      targetRevision: feature/signalilo
    victoriametricsalertmanager:
      targetRevision: feature/signalilo

    # external repos
    begetcmprovider:
      targetRevision: v0.0.4
    ccm:
      targetRevision: HEAD
    certcontrollermanager:
      targetRevision: HEAD
    csrc:
      targetRevision: HEAD
    istiobase:
      targetRevision: 1.26.0
    secretcopyoperator:
      targetRevision: HEAD

xclusterComponents:
  client:
    enabled: false
