composition:
  developmentMode: false
  compositionRevisionNumber: 0
  xaddonset:
    debug: false
  xcertificate:
    debug: false
  xcertificateset:
    debug: false

composite:
  addons:
    common:
      targetRevision: v0.0.5

    # feature/tg-alerting
    crossplanecompositions:
      targetRevision: feature/tg-alerting
    victoriametricsalertmanager:
      targetRevision: feature/tg-alerting
    victoriametricsalertrules:
      targetRevision: feature/tg-alerting
    victoriametricscluster:
      targetRevision: feature/tg-alerting

    # external repos
    begetcmprovider:
      targetRevision: v0.0.4
    ccm:
      targetRevision: HEAD
    certcontrollermanager:
      targetRevision: HEAD
    csrc:
      targetRevision: HEAD
    istiobase:
      targetRevision: 1.26.0
    secretcopyoperator:
      targetRevision: HEAD

xclusterComponents:
  client:
    enabled: false
