companyPrefix: example
companyDomain: example.com
companyExternalChartRegistry: example.com
companyInternalChartRegistry: example.com
companyInternalChartRegistryPublic: example.com
companyInternalDockerRegistry: example.com
companyExternalGitRepository: example.com
companyInternalGitRepository: example.com
companyWikiAlertingUrl: example.com
companyAdminUser: adm@example.com

addons:
  addonsoperator:
    enabled: false
  addonmanifests:
    enabled: false
  addonset:
    enabled: false
  argocd:
    enabled: false
  cmprovider:
    enabled: false
  certificateset:
    enabled: false
  certmanager:
    enabled: false
  certmanagercsidriver:
    enabled: false
  cilium:
    enabled: false
  coredns:
    enabled: false
  clientkubestatemetrics:
    enabled: false
  clientvmscrapeconfig:
    enabled: false
  clusterclaimoperator:
    enabled: false
  ccmcsrcsystem:
    enabled: false
  ccmcsrccontroller:
    enabled: false
  capi:
    enabled: false
  capiclusterclass:
    enabled: false
  capikubeadmbootstrap:
    enabled: false
  capikubeadmcontrolplane:
    enabled: false
  controlplane:
    enabled: false
  dex:
    enabled: false
  dockerregistry:
    enabled: false
  etcdbackupsnapshot:
    enabled: false
  extraresources:
    enabled: false
  helminserter:
    enabled: false
  grafana:
    enabled: false
  grafanadashboards:
    enabled: false
  grafanaoperator:
    enabled: false
  kubestatemetrics:
    enabled: false
  konnectivityagent:
    enabled: false
  metricsserver:
    enabled: false
  prometheusprocessexporter:
    enabled: false
  prometheusnodeexporter:
    enabled: false
  incloudwebchart:
    enabled: false
  incloudwebresources:
    enabled: false
  istiobase:
    enabled: false
  istiod:
    enabled: false
  istiogw:
    enabled: false
  secretcopyoperator:
    enabled: false
  signalilo:
    enabled: false
  svck8sproxy:
    enabled: false
  svchub:
    enabled: false
  template:
    enabled: false
  test:
    enabled: false
  trustmanager:
    enabled: false
  vmagent:
    enabled: false
  vmagentadditionalrbac:
    enabled: false
  trivyoperator:
    enabled: false
  vmoperator:
    enabled: false
  vault:
    enabled: false
  validatingadmissionpolicies:
    enabled: false
  vmalert:
    enabled: false
  vmalertmanager:
    enabled: false
  vmalertrules:
    enabled: false
  vmcluster:
    enabled: false
  vmauth:
    enabled: true
  system:
    enabled: true
  workergroupclaimoperator:
    enabled: false
environment: infra
clusterClaim: cluster
clientName: client
clusterName: infra
addonRevision: 0.1.0
clientClusterEnabled: false
