{{- if .Values.metrics.enable }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "cluster-claim-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: controller-manager
  name: {{ include "cluster-claim-operator.resourceName" (dict "suffix" "controller-manager-metrics-monitor" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https-metrics
    scheme: HTTPS
    tlsConfig:
      serverName: {{ include "cluster-claim-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}.{{ .Release.Namespace }}.svc
      {{- if .Values.certManager.enable }}
      insecureSkipVerify: false
      ca:
        secret:
          name: metrics-server-cert
          key: ca.crt
      cert:
        secret:
          name: metrics-server-cert
          key: tls.crt
      keySecret:
        name: metrics-server-cert
        key: tls.key
      {{- else }}
      insecureSkipVerify: true
      {{- end }}
      {{- with .Values.monitoring.serviceScrapeConfig.metricRelabelConfigs }}
      metricRelabelConfigs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  jobLabel: cluster-claim-operator
  selector:
    matchLabels:
      monitoring.in-cloud.io/service: {{ include "cluster-claim-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}
      app.kubernetes.io/name: {{ include "cluster-claim-operator.name" . }}
      control-plane: controller-manager
{{- end }}
