companyPrefix: example

signalilo:
  config:
    icinga_url: ""
# some values for signalilo

networkPolicies:
  enabled: false

secrets: {}
#   icinga_username: ""
#   icinga_password: ""
#   alertmanager_bearer_token: ""
