{{- if .Values.metrics.enable }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "svc-tls" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "svc-tls" "context" $) }}
  duration: 8760h
  renewBefore: 720h
  commonName: {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}
  dnsNames:
    - {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}
    - {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}.{{ .Release.Namespace }}
    - {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}.{{ .Release.Namespace }}.svc
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    kind: {{ .Values.monitoring.secureService.issuer.kind }}
    name: {{ .Values.monitoring.secureService.issuer.name }}
{{- end }}
