{{- if .Values.monitoring.secureService.enabled }}
{{- $svcName := .Values.coredns.service.name | default (include "coredns-wrapper.fullname" .) }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-metrics-svc-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: coredns-metrics-svc-tls
  duration: 8760h
  renewBefore: 720h
  commonName: {{ $svcName }}-monitoring
  dnsNames:
    - {{ $svcName }}-monitoring
    - {{ $svcName }}-monitoring.{{ .Release.Namespace }}
    - {{ $svcName }}-monitoring.{{ .Release.Namespace }}.svc
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    kind: {{ .Values.monitoring.secureService.issuer.kind }}
    name: {{ .Values.monitoring.secureService.issuer.name }}
{{- end }}
