{{ if .Values.networkPolicies.enabled }}

---
# Allow `vmagent` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-vmagent-to-coredns-11043
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '11043'
        protocol: TCP
  egress:
  - {}
  description: Allows egress for vmagent to coredns on port 11043 for scrape metrics.

---
# Allow `vmagent` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-vmagent-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows egress for vmagent to coredns on port 53 for scrape metrics.

---
# Allow `argocd-repo-server` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-argocd-repo-server-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: argocd-repo-server
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-argocd
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows egress for argocd-repo-server to coredns on port 53 for DNS resolution.

---
# Allow `argocd-application-controller` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-argocd-application-controller-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: argocd-application-controller
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-argocd
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows egress for argocd-application-controller to coredns on port 53 for DNS resolution.

---
# Allow `argocd-application-controller` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-argocd-application-controller-to-coredns-icmpv4
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: argocd-application-controller
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-argocd
    icmps:
    - fields:
      - type: 8
        family: IPv4
  egress:
  - {}
  description: Allows egress for argocd-application-controller to coredns on port 53 for DNS resolution.

---
# Allow `argocd-server` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-argocd-server-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: argocd-server
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-argocd
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows egress for argocd-server to coredns on port 53 for DNS resolution.

---
# Allow `istio-gw` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-istio-gw-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: istio-gw
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-istio-gw
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows egress for istio-gw to coredns on port 53 for DNS resolution.

---
# Allow `client-kube-state-metrics` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-client-kube-state-metrics-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: client-kube-state-metrics
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-client-kube-state-metrics
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows egress for client-kube-state-metrics to coredns on port 53 for DNS resolution.

---
# Allow `kube-state-metrics` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-kube-state-metrics-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: kube-state-metrics
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-kube-state-metrics
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows egress for kube-state-metrics to coredns on port 53 for DNS resolution.

---
apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: external-dns
spec:
  externalCIDRs:
    - "8.8.8.8/32"

---
# Allow `istio-gw` to coredns.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-coredns-to-external-dns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - {}
  egress:
  - toCIDRSet:
    - cidrGroupRef: external-dns
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  description: Allows egress for coredns to external-dns on port 53 for DNS resolution.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-coredns-to-kube-apiserver-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - {}
  egress:
  - toEntities:
    - kube-apiserver
    - remote-node
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress for coredns to kube-apiserver on port 6443.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-remote-node-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEntities:
    - remote-node
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows egress for remote-node to coredns on port 53 for DNS resolution.

---
# Allow `etcd-backup` to resolve DNS via CoreDNS.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-etcd-backup-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: default
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-etcd-backup-snapshot
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows ingress from etcd-backup to CoreDNS on 53 for DNS resolution.

---
# Allow `hubble-relay` to resolve DNS via CoreDNS.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-hubble-relay-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: hubble-relay
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-cilium
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows ingress from hubble-relay to CoreDNS on 53 for DNS resolution.

---
# Allow `hubble-ui` to resolve DNS via CoreDNS.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-hubble-ui-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: hubble-ui
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-cilium
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows ingress from hubble-ui to CoreDNS on 53 for DNS resolution.

---
# Allow ``incloud-ui` to resolve DNS via CoreDNS.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-incloud-ui-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: coredns
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: incloud-web-chart-incloud-web-chart
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-incloud-web-chart
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
  egress:
  - {}
  description: Allows ingress from incloud-ui to CoreDNS on 53 for DNS resolution.


{{- end }}