{{- if .Values.monitoring.enabled }}
{{- $coredns := .Values.coredns }}
{{- $svcName := $coredns.service.name | default (include "coredns-wrapper.fullname" .) }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    monitoring.in-cloud.io/service: coredns
spec:
  ports:
    - name: https-metrics
      port: 11043
      protocol: TCP
      targetPort: https-metrics
  selector:
    {{- if $coredns.service.selector }}
    {{- toYaml .Values.service.selector | nindent 4 }}
    {{- else }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    {{- if .Values.isClusterService }}
    k8s-app: {{ template "coredns-wrapper.k8sapplabel" . }}
    {{- end }}
    app.kubernetes.io/name: {{ template "coredns-wrapper.name" . }}
    {{- end }}
{{- end }}
