---
# Source: addonset/templates/addonsClient/konnectivity-agent/konnectivity-agent.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: konnectivity-agent
spec:
  chart: "konnectivity-agent"
  pluginName: helm-with-values
  repoURL: "example.com"
  version: "0.1.0"
  releaseName: konnectivity-agent
  targetCluster: client
  targetNamespace: "example-konnectivity-agent"
  variables:
    cluster_name: client
  valuesSources:
    - name: parameters
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-client
        namespace: example-system
      extract:
        - as: companyPrefix
          jsonPath: .data.companyPrefix
        - as: companyDomain
          jsonPath: .data.companyDomain
  initDependencies:
    - name: addons-operator
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: true
    - name: addonset
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: true
    - name: client-cp-control-plane
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
  valuesSources:
    - name: parameters-client
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-client
        namespace: example-system
      extract:
        - as: cluster.host
          jsonPath: .data.clusterHost
        - as: cluster.name
          jsonPath: .data.clusterName
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/clusterName: client
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: konnectivity-agent
    - name: custom
      priority: 90
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: konnectivity-agent
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: konnectivity-agent
---
# Source: addonset/templates/addonsClient/konnectivity-agent/konnectivity-agent.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: konnectivity-agent-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: konnectivity-agent
spec:
  values: ""
---
# Source: addonset/templates/addonsClient/konnectivity-agent/konnectivity-agent.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: konnectivity-agent-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: konnectivity-agent
spec:
  values: |
    hostNetwork: true
    agent:
      extraArgs:
        proxy-server-host: {{ .Values.cluster.host }}
        proxy-server-port: 8132
---
# Source: addonset/templates/addonsClient/konnectivity-agent/konnectivity-agent.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: konnectivity-agent-client
  labels:
    addons.in-cloud.io/values: client
    addons.in-cloud.io/addon: konnectivity-agent
spec:
  values: |
    tolerations:
      - operator: "Exists"
    labels:
      toleration.{{ .Values.companyDomain }}/ignore: "true"
    podLabels:
      toleration.{{ .Values.companyDomain }}/ignore: "true"
