{{- if .Values.nodelabelsController.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "node-labels-controller-manager-role" "context" $) }}
rules:
    - apiGroups:
        - ""
      resources:
        - events
      verbs:
        - create
        - patch
    - apiGroups:
        - ""
      resources:
        - secrets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - workergroup.in-cloud.io
      resources:
        - nodelabelpolicies
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - workergroup.in-cloud.io
      resources:
        - nodelabelpolicies/status
      verbs:
        - get
        - patch
        - update
    - apiGroups:
        - cluster.x-k8s.io
      resources:
        - machines
        - machinesets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - cluster.x-k8s.io
      resources:
        - machinedeployments
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
{{- end }}


2026-08-04T18:29:50Z	ERROR	controller-runtime.cache.UnhandledError	Failed to watch	{"reflector": "pkg/mod/k8s.io/client-go@v0.34.3/tools/cache/reflector.go:290", "type": "*v1.Secret", "error": "failed to list *v1.Secret: secrets is forbidden: User \"system:serviceaccount:beget-worker-group-claim-operator:worker-group-claim-operator-node-labels-controller-manager\" cannot list resource \"secrets\" in API group \"\" at the cluster scope"}
