---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: metrics-server-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: metrics-server
spec:
  values: |
    metrics-server:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: metrics-server-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: metrics-server
spec:
  values: ""

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: metrics-server-infra
  labels:
    addons.in-cloud.io/values: infra
    addons.in-cloud.io/addon: metrics-server
spec:
  values: |
    metrics-server:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: metrics-server-client
  labels:
    addons.in-cloud.io/values: client
    addons.in-cloud.io/addon: metrics-server
spec:
  values: |
    metrics-server:
      podLabels:
        toleration.beget.com/ignore: "true"
      tolerations:
        - operator: "Exists"

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: metrics-server-vm-operator
  labels:
    addons.in-cloud.io/values: vm-operator
    addons.in-cloud.io/addon: metrics-server
spec:
  values: |
    monitoring:
      enabled: true
      secureService:
        enabled: true
        issuer:
          name: selfsigned-cluster-issuer
