---
# Source: addonset/templates/addons/ccm-csrc-controller/addon.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: ccm-csrc-controller
spec:
  chart: ccm-csr-controller
  pluginName: helm-with-values
  repoURL: "example.com"
  version: "0.1.1"
  targetCluster: in-cluster
  releaseName: system
  targetNamespace: "example-ccm-csrc-controller"
  variables:
    cluster_name: in-cluster
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: ccm-csrc-controller
    - name: custom
      priority: 90
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: ccm-csrc-controller
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: ccm-csrc-controller
  valuesSources:
    - name: parameters-infra
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-infra
        namespace: example-system
      extract:
        - as: companyInternalDockerRegistry
          jsonPath: .data.companyInternalDockerRegistry
---
# Source: addonset/templates/addons/ccm-csrc-controller/phase.client.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: coredns-client
spec:
  rules:
---
# Source: addonset/templates/addons/ccm-csrc-controller/phase.infra.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: ccm-csrc-controller
spec:
  rules:
---
# Source: addonset/templates/addons/ccm-csrc-controller/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: ccm-csrc-controller-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: ccm-csrc-controller
spec:
  values: |
    controllerManager:
      manager:
        image:
          repository: {{ .Values.companyInternalDockerRegistry }}/k8s-charts-public/charts/ccm-csr-controller
        resources:
          limits:
            cpu: 6 # In trottling case need delete limits.cpu
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 512Mi
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
---
# Source: addonset/templates/addons/ccm-csrc-controller/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: ccm-csrc-controller-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: ccm-csrc-controller
spec:
  values: |
