dex: {}

companyPrefix: example

networkPolicies:
  enabled: false


monitoring:
  serviceScrapeConfig:
    metricRelabelConfigs:
      - sourceLabels: [__name__]
        action: keep
        regex: |
          container_cpu_cfs_periods_total|
          container_cpu_cfs_throttled_periods_total|
          container_cpu_cfs_throttled_seconds_total|
          container_cpu_usage_seconds_total|
          container_memory_rss|
          container_memory_working_set_bytes|
          container_network_receive_bytes_total|
          container_network_receive_errors_total|
          container_network_receive_packets_dropped_total|
          container_network_receive_packets_total|
          container_network_transmit_bytes_total|
          container_network_transmit_errors_total|
          container_network_transmit_packets_dropped_total|
          container_network_transmit_packets_total|
          container_oom_events_total|
          go_gc_duration_seconds_count|
          go_gc_duration_seconds_sum|
          go_goroutines|
          go_memstats_alloc_bytes_total|
          go_memstats_gc_sys_bytes|
          go_memstats_heap_idle_bytes|
          go_memstats_heap_inuse_bytes|
          go_memstats_heap_released_bytes|
          go_memstats_mcache_sys_bytes|
          go_memstats_mspan_sys_bytes|
          go_memstats_other_sys_bytes|
          go_memstats_stack_inuse_bytes|
          go_memstats_sys_bytes|
          kube_service_info|
          namespace_cpu|
          namespace_memory|
          node_namespace_pod:kube_pod_info:|
          process_cpu_seconds_total|
          process_max_fds|
          process_open_fds|
          process_resident_memory_bytes|
          process_start_time_seconds|
          process_virtual_memory_bytes|
          scrape_series_added|
          up
  enabled: false
  type: VictoriaMetrics
  secureService:
    enabled: false
    # Create a secret containing both 'tls.crt' and 'tls.key' fields
    issuer:
      kind: ClusterIssuer
      name: default

tls:
  enabled: false
  issuer:
    name: default-issuer-name
    secretName: default-secret-name
  certificate:
    name: dex-tls
    secretName: dex-tls
    duration: 8760h
    renewBefore: 720h
    commonName: dex
    dnsNames:
      - dex.default.svc
      - dex.default.svc.cluster.local

rbac:
  enabled: false
  clusterRoleBinding:
    subjects:
      kind: User
      name: default-user

istio:
  virtualService:
    enabled: false
    gateways:
      - default-ns/default
    hosts:
      - "*"
    http:
      name: dex
      route:
        host: dex
        port: 5554
  destinationRule:
    enabled: false
    host: dex
    trafficPolicy:
      tls:
        mode: SIMPLE
        insecureSkipVerify: true