{{- if and .Values.metrics.enable .Values.workergroupsController.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "workergroups-controller-metrics-reader" "context" $) }}
rules:
    - nonResourceURLs:
        - /metrics
      verbs:
        - get
{{- end }}
