{{- if and .Values.metrics.enable .Values.workergroupsController.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ include "worker-group-claim-operator.resourceName" (dict "suffix" "workergroups-controller-metrics-auth-role" "context" $) }}
rules:
    - apiGroups:
        - authentication.k8s.io
      resources:
        - tokenreviews
      verbs:
        - create
    - apiGroups:
        - authorization.k8s.io
      resources:
        - subjectaccessreviews
      verbs:
        - create
{{- end }}
