{{- if .Values.addons.coredns.enabled }}
  {{- range $name := list
    "default"
    "immutable"
    "infra"
    "network-policies"
    "client"
    "initialized"
    "vm-operator"
    "system"
    "multi-control-plane"
  }}
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: coredns-{{ $name }}
  labels:
    addons.in-cloud.io/values: {{ $name }}
    addons.in-cloud.io/addon: coredns
spec:
  values: |
    {{- $.Files.Get (printf "files/coredns/%s.goyaml" $name) | nindent 4 }}
  {{- end }}

{{- end }}
