argocdDestinationNamespace: ""
extraArgs:
  argocdServerAdminPassword: ""
  dexStaticClientsApiserver: ""
  dexStaticPasswordsAdmin: ""
  dockerRegistryS3AccessKey: ""
  dockerRegistryS3SecretKey: ""
  dockerRegistryS3Bucket: ""
  etcdbackupAppArgsStorecontainer: ""
  etcdbackupS3AccessKey: ""
  etcdbackupS3SecretAccessKey: ""
  etcdbackupS3SecretEndpoint: ""
  grafanaConfigAdminPassword: ""
  grafanaConfigAdminUser: ""
  grafanaDeploymentEnvOidcSecret: ""
  incloudUICookieSecret: ""
  systemIstioGwDomain: ""
  systemIstioGwVip: ""
  systemIstioGwVipInternal: ""
  systemIstioGwDomainInternal: ""
  systemVmInsertVIP: ""
  companyPrefix: ""
  companyDomain: ""
  companyExternalChartRegistry: ""
  companyInternalChartRegistry: ""
  companyInternalChartRegistryPublic: ""
  companyInternalDockerRegistry: ""
  companyExternalGitRepository: ""
  companyInternalGitRepository: ""
  companyWikiAlertingUrl: ""
  companyAdminUser: ""
versions:
  addonRevision: ""
  clientControlPlane: ""
  componentVersions: ""
  kubernetes: ""
  runc: ""
  containerd: ""
  crictl: ""
  pause: ""
  etcd: ""
  kubeadm: ""
  kubectl: ""
  kubelet: ""
  kubeApiServer: ""
  kubeControllerManager: ""
  kubeScheduler: ""
#versionMode: static/dynamic
versionMode: static
