argocdDestinationNamespace: ""
templates:
  ccmcsr:
    enabled: true
  certificatesetclient:
    enabled: true
  certificatesetinfra:
    enabled: true
  clusterclient:
    enabled: true
  clusterinfra:
    enabled: true
  configmapclient:
    enabled: true
  configmapinfra:
    enabled: true
  observe:
    enabled: true
  vaultclaim:
    enabled: true
  vaultsecretclaim:
    enabled: true
extraArgs:
  argocdServerAdminPassword: ""
  dexStaticClientsApiserver: ""
  dexStaticPasswordsAdmin: ""
  dockerRegistryS3AccessKey: ""
  dockerRegistryS3SecretKey: ""
  dockerRegistryS3Bucket: ""
  etcdbackupAppArgsStorecontainer: ""
  etcdbackupS3AccessKey: ""
  etcdbackupS3SecretAccessKey: ""
  etcdbackupS3SecretEndpoint: ""
  grafanaConfigAdminPassword: ""
  grafanaConfigAdminUser: ""
  grafanaDeploymentEnvOidcSecret: ""
  incloudUICookieSecret: ""
  ipamMode: ""
  systemIstioGwDomain: ""
  systemIstioGwVip: ""
  systemIstioGwVipInternal: "1.1.1.1"
  systemIstioGwDomainInternal: "example.com"
  systemVmInsertVIP: ""
  systemClusterName: ""
  companyPrefix: ""
  companyDomain: ""
  companyExternalChartRegistry: ""
  companyInternalDockerRegistry: ""
  companyExternalGitRepository: ""
  companyWikiAlertingUrl: ""
  companyAdminUser: ""
versions:
  addonRevision: ""
  ccm: ""
  clientControlPlane: ""
  componentVersions: ""
  kubernetes: ""
  runc: ""
  containerd: ""
  crictl: ""
  csrc: ""
  pause: ""
  etcd: ""
  kubeadm: ""
  kubectl: ""
  kubelet: ""
  kubeApiServer: ""
  kubeControllerManager: ""
  kubeScheduler: ""
#versionMode: static/dynamic
versionMode: static
