---
# Source: addonset/templates/addons/cilium/addon.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: cilium
spec:
  chart: "cilium"
  repoURL: "example.com"
  version: "1.18.5-2"
  pluginName: helm-with-values
  targetCluster: in-cluster
  targetNamespace: "example-cilium"
  variables:
    dependency: "True"
  valuesSources:
    - name: parameters-infra
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-infra
        namespace: example-system
      extract:
        - as: cluster.host
          jsonPath: .data.clusterHost
        - as: cluster.name
          jsonPath: .data.clusterName
        - as: cluster.port
          jsonPath: .data.clusterPort #tmp need change -> clusterPort for prod-ready (infra) or clusterClientPort
        - as: podCidr
          jsonPath: .data.podCidr
        - as: podCidrMaskSize
          jsonPath: .data.podCidrMaskSize
        - as: companyPrefix
          jsonPath: .data.companyPrefix
        - as: companyDomain
          jsonPath: .data.companyDomain
  initDependencies:
    - name: addons-operator
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: true
    - name: addonset
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: true
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
    ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: Service
      jqPathExpressions:
        - .spec.ports[]?.nodePort
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: cilium
    - name: custom
      priority: 95
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: cilium
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: cilium
---
# Source: addonset/templates/addons/cilium/phase.client.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: cilium-client
spec:
  rules:
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.status.phaseValuesSelector[?(@.name=='initialized-2')]
          operator: Exists
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator-client
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 45
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: cilium
---
# Source: addonset/templates/addons/cilium/phase.infra.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: cilium
spec:
  rules:
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.status.phaseValuesSelector[?(@.name=='initialized-2')]
          operator: Exists
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 45
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: cilium
    - name: network-policies
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.environment
          operator: Equal
          value: "infra"
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cilium
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cilium
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: AddonPhase
            name: extra-resources
          jsonPath: $.status.ruleStatuses[?(@.name=='network-policies-argocd')].deployed
          operator: Equal
          value: true
      selector:
        name: network-policies
        priority: 65
        matchLabels:
          addons.in-cloud.io/values: network-policies
          addons.in-cloud.io/addon: cilium
    - name: enforcement-always
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.environment
          operator: Equal
          value: "infra"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: AddonPhase
            name: coredns
          jsonPath: $.status.ruleStatuses[?(@.name=='network-policies')].deployed
          operator: Equal
          value: true
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: AddonPhase
            name: argocd
          jsonPath: $.status.ruleStatuses[?(@.name=='network-policies')].deployed
          operator: Equal
          value: true
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: AddonPhase
            name: addons-operator
          jsonPath: $.status.ruleStatuses[?(@.name=='network-policies')].deployed
          operator: Equal
          value: true
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: AddonPhase
            name: cilium
          jsonPath: $.status.ruleStatuses[?(@.name=='network-policies')].deployed
          operator: Equal
          value: true
      selector:
        name: enforcement-always
        priority: 80
        matchLabels:
          addons.in-cloud.io/values: enforcement-always
          addons.in-cloud.io/addon: cilium
---
# Source: addonset/templates/addons/cilium/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: cilium-client
  labels:
    addons.in-cloud.io/values: client
    addons.in-cloud.io/addon: cilium
spec:
  values: |
    cilium:
      podLabels:
        toleration.{{ .Values.companyDomain }}/ignore: "true"
      operator:
        podLabels:
          toleration.{{ .Values.companyDomain }}/ignore: "true"
        tolerations:
          - operator: Exists
          - key: "node-role.kubernetes.io/control-plane"
            operator: Exists
          - key: "node-role.kubernetes.io/master" #deprecated
            operator: Exists
          - key: "node.kubernetes.io/not-ready"
            operator: Exists
          - key: "node.cloudprovider.kubernetes.io/uninitialized"
            operator: Exists
---
# Source: addonset/templates/addons/cilium/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: cilium-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: cilium
spec:
  values: |
    cilium:
      ciliumEndpointSlice:
        enabled: true
      image:
        pullPolicy: IfNotPresent
      envoy:
        enabled: false
      hubble:
        enabled: false
      kubeProxyReplacement: true
      podLabels:
        in-cloud.io/clusterName: "{{ .Values.cluster.name }}"
      nodePort:
        enabled: true
      operator:
        replicas: 1
        image:
          pullPolicy: IfNotPresent
      dnsPolicy: ClusterFirstWithHostNet
      prometheus:
        metricsService: true
        enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      tls:
        readSecretsOnlyFromSecretsNamespace: false
        secretSync:
          enabled: false
        secretsNamespace:
          create: false
          name: ~
---
# Source: addonset/templates/addons/cilium/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: cilium-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: cilium
spec:
  values: |
    cilium:
      k8sServiceHost: "{{ .Values.cluster.host }}"
      k8sServicePort: "{{ .Values.cluster.port }}"
      ipam:
        operator:
          clusterPoolIPv4MaskSize: {{ .Values.podCidrMaskSize }}
          clusterPoolIPv4PodCIDRList: [ "{{ .Values.podCidr }}" ]
---
# Source: addonset/templates/addons/cilium/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: cilium-network-policies
  labels:
    addons.in-cloud.io/values: network-policies
    addons.in-cloud.io/addon: cilium
spec:
  values: |

    companyPrefix: {{ .Values.companyPrefix }}
    networkPolicies:
      enabled: true
---
# Source: addonset/templates/addons/cilium/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: cilium-vm-operator
  labels:
    addons.in-cloud.io/values: vm-operator
    addons.in-cloud.io/addon: cilium
spec:
  values: |
    argocdPlugins:
      kustomize: true
    cilium:
      extraContainers:
        - name: rbac-proxy
          image: quay.io/brancz/kube-rbac-proxy:v0.21.0
          args:
            - --secure-listen-address=0.0.0.0:11043
            - --upstream=http://127.0.0.1:9962
            - --tls-cert-file=/app/config/metrics/tls/tls.crt
            - --tls-private-key-file=/app/config/metrics/tls/tls.key
            - --v=2
          ports:
            - name: https-metrics
              containerPort: 11043
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          volumeMounts:
            - name: rbac-proxy-tls
              mountPath: /app/config/metrics/tls
              readOnly: true
      extraVolumes:
        - name: rbac-proxy-tls
          secret:
            defaultMode: 420
            secretName: cilium-agent-svc-tls

    monitoring:
      enabled: true
      secureService:
        enabled: true
        issuer:
          name: selfsigned-cluster-issuer
---
# Source: addonset/templates/addons/cilium/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: cilium-enforcement-always
  labels:
    addons.in-cloud.io/values: enforcement-always
    addons.in-cloud.io/addon: cilium
spec:
  values: |
    cilium:
      policyEnforcementMode: always
