{{- if .Values.networkPolicies.enabled }}
{{- $fullname := include "docker-registry.fullname" . }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-docker-registry-cache-registry-{{ .Values.companyPrefix }}-ru-from-vmagent-11043
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $fullname }}-registry-{{ .Values.companyPrefix }}-ru
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '11043'
        protocol: TCP
  description: Allows ingress from vmagent to the registry-{{ .Values.companyPrefix }}-ru
    cache on 11043 for metrics collection.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-docker-registry-cache-registry-{{ .Values.companyPrefix }}-ru-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $fullname }}-registry-{{ .Values.companyPrefix }}-ru
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: '53'
        protocol: UDP
      - port: '53'
        protocol: TCP
  description: Allows egress from the registry-{{ .Values.companyPrefix }}-ru cache
    to CoreDNS on 53 for DNS resolution.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-docker-registry-cache-registry-{{ .Values.companyPrefix }}-ru-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $fullname }}-registry-{{ .Values.companyPrefix }}-ru
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from the registry-{{ .Values.companyPrefix }}-ru cache
    to the Kubernetes API server on 6443.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-docker-registry-cache-registry-{{ .Values.companyPrefix }}-ru-to-upstream-443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ $fullname }}-registry-{{ .Values.companyPrefix }}-ru
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toFQDNs:
    - matchName: registry.{{ .Values.companyPrefix }}.ru
    - matchPattern: '*.{{ .Values.companyPrefix }}.ru'
    toPorts:
    - ports:
      - port: '443'
        protocol: TCP
  description: Allows egress from the registry-{{ .Values.companyPrefix }}-ru cache
    to registry.{{ .Values.companyPrefix }}.ru on 443.
{{- end }}
