---
apiVersion: clusterclaim.in-cloud.io/v1alpha1
kind: ClusterClaimObserveResourceTemplate
metadata:
  name: {{ .Release.Name }}-cm-infra
spec:
  apiVersion: v1
  kind: ConfigMap
  value: |
    metadata:
      labels:
        xcluster.in-cloud.io/name: {{`{{ .ClusterClaim.metadata.name }}`}}
    data:
      environment: infra
      xcluster: {{`{{ .ClusterClaim.metadata.name }}`}}
      customer: {{`{{ .ClusterClaim.metadata.namespace }}`}}
      systemNamespace: {{`{{ .ClusterClaim.metadata.namespace }}`}}

      clusterName: {{`{{ .ClusterClaim.metadata.name }}`}}-infra
      clusterHost: {{`{{ .InfraControlPlaneEndpoint.Host }}`}}
      clusterPort: "{{`{{ .ClusterClaim.spec.infra.network.kubeApiserverPort }}`}}"
      controlPlaneAvailableReplicas: "{{`{{ .InfraControlPlaneAvailableReplicas }}`}}"
      controlPlaneDesiredReplicas: "{{`{{ .InfraControlPlaneDesiredReplicas }}`}}"

      clusterClientEnabled: "{{`{{ .ClusterClaim.spec.client.enabled }}`}}"
      clusterClientName: {{`{{ .ClusterClaim.metadata.name }}`}}-client
    {{`{{- if .ClusterClaim.spec.client.enabled }}`}}
      clusterClientPort: "{{`{{ .ClusterClaim.spec.client.network.kubeApiserverPort }}`}}"
      clientServiceCidr: {{`{{ .ClusterClaim.spec.client.network.serviceCidr }}`}}
      dexStaticClientsApiserver: {{ .Values.extraArgs.dexStaticClientsApiserver }}
    {{`{{- end }}`}}

      clusterDNS: {{`{{ .ClusterClaim.spec.infra.network.clusterDNS }}`}}
      serviceCidr: {{`{{ .ClusterClaim.spec.infra.network.serviceCidr }}`}}
      podCidr: {{`{{ .ClusterClaim.spec.infra.network.podCidr }}`}}
      podCidrMaskSize: "{{`{{ .ClusterClaim.spec.infra.network.podCidrMaskSize }}`}}"

      argocdDestinationName: {{`{{ .ClusterClaim.metadata.name }}`}}-infra
      argocdDestinationNamespace: {{ .Values.argocdDestinationNamespace }}
      addonRevision: {{ .Values.versions.addonRevision }}
      trackingID: {{`{{ .ClusterClaim.metadata.namespace }}`}}_{{`{{ .ClusterClaim.metadata.name }}`}}:argoproj.io/Application:{{`{{ .ClusterClaim.metadata.namespace }}`}}/{{`{{ .ClusterClaim.metadata.name }}`}}

      systemEnabled: "{{`{{ hasPrefix "system" .ClusterClaim.spec.infra.role }}`}}"
      argocdServerAdminPassword: {{ .Values.extraArgs.argocdServerAdminPassword }}
      dexStaticPasswordsAdmin: {{ .Values.extraArgs.dexStaticPasswordsAdmin }}
      etcdbackupAppArgsStorecontainer: {{ .Values.extraArgs.etcdbackupAppArgsStorecontainer }}
      etcdbackupS3AccessKey: {{ .Values.extraArgs.etcdbackupS3AccessKey }}
      etcdbackupS3SecretAccessKey: {{ .Values.extraArgs.etcdbackupS3SecretAccessKey }}
      etcdbackupS3SecretEndpoint: {{ .Values.extraArgs.etcdbackupS3SecretEndpoint }}
      grafanaConfigAdminPassword: {{ .Values.extraArgs.grafanaConfigAdminPassword }}
      grafanaConfigAdminUser: {{ .Values.extraArgs.grafanaConfigAdminUser }}
      grafanaDeploymentEnvOidcSecret: {{ .Values.extraArgs.grafanaDeploymentEnvOidcSecret }}
      incloudUICookieSecret: {{ .Values.extraArgs.incloudUICookieSecret }}
      companyPrefix: {{ .Values.extraArgs.companyPrefix }}
      companyDomain: {{ .Values.extraArgs.companyDomain }}
      companyExternalChartRegistry: {{ .Values.extraArgs.companyExternalChartRegistry }}
      companyInternalChartRegistry: {{ .Values.extraArgs.companyInternalChartRegistry }}
      companyInternalChartRegistryPublic: {{ .Values.extraArgs.companyInternalChartRegistryPublic }}
      companyInternalDockerRegistry: {{ .Values.extraArgs.companyInternalDockerRegistry }}
      companyExternalGitRepository: {{ .Values.extraArgs.companyExternalGitRepository }}
      companyInternalGitRepository: {{ .Values.extraArgs.companyInternalGitRepository }}
      companyWikiAlertingUrl: {{ .Values.extraArgs.companyWikiAlertingUrl }}
      companyAdminUser: {{ .Values.extraArgs.companyAdminUser }}
    {{`{{- if eq .ClusterClaim.spec.infra.role "system" }}`}}
      dockerRegistryS3AccessKey: {{ .Values.extraArgs.dockerRegistryS3AccessKey }}
      dockerRegistryS3SecretKey: {{ .Values.extraArgs.dockerRegistryS3SecretKey }}
      dockerRegistryS3Bucket: {{ .Values.extraArgs.dockerRegistryS3Bucket }}
      signaliloUuid: "{{`{{ .ClusterClaim.spec.extraEnvs.signaliloUuid }}`}}"
      icingaHostname: {{`{{ .ClusterClaim.spec.extraEnvs.icingaHostname }}`}}
      icingaUrl: {{`{{ .ClusterClaim.spec.extraEnvs.icingaUrl }}`}}
      icingaUsername: "{{`{{ .ClusterClaim.spec.extraEnvs.icingaUsername }}`}}"
      icingaPassword: {{`{{ .ClusterClaim.spec.extraEnvs.icingaPassword }}`}}
      alertmanagerSignaliloPort: {{`{{ .ClusterClaim.spec.extraEnvs.alertmanagerSignaliloPort }}`}}
      alertmanagerSignaliloToken: "{{`{{ .ClusterClaim.spec.extraEnvs.alertmanagerSignaliloToken }}`}}"
      svcHubRabbitUsername: {{`{{ .ClusterClaim.spec.extraEnvs.svcHubRabbitUsername }}`}}
      svcHubRabbitPassword: {{`{{ .ClusterClaim.spec.extraEnvs.svcHubRabbitPassword | quote }}`}}
      svcHubRabbitHost: {{`{{ .ClusterClaim.spec.extraEnvs.svcHubRabbitHost }}`}}
      svcHubRabbitVirtualHost: "{{`{{ .ClusterClaim.spec.extraEnvs.svcHubRabbitVirtualHost }}`}}"
      telegramToken: {{`{{ .ClusterClaim.spec.extraEnvs.telegramToken }}`}}
      telegramChatId: {{`{{ .ClusterClaim.spec.extraEnvs.telegramChatId | quote }}`}}
    {{`{{- if (index .ClusterClaim.spec.extraEnvs "systemIstioGwVipInternal") }}`}}
      systemIstioGwVipInternal: {{`{{ .ClusterClaim.spec.extraEnvs.systemIstioGwVipInternal }}`}}
    {{`{{- else }}`}}
      systemIstioGwVipInternal: {{ .Values.extraArgs.systemIstioGwVipInternal }}
    {{`{{- end }}`}}
    {{`{{- if (index .ClusterClaim.spec.extraEnvs "systemIstioGwDomainInternal") }}`}}
      systemIstioGwDomainInternal: {{`{{ .ClusterClaim.spec.extraEnvs.systemIstioGwDomainInternal }}`}}
    {{`{{- else }}`}}
      systemIstioGwDomainInternal: {{ .Values.extraArgs.systemIstioGwDomainInternal }}
    {{`{{- end }}`}}
    {{`{{- end }}`}}

    {{`{{- if (index .ClusterClaim.spec.extraEnvs "systemIstioGwVip") }}`}}
      systemIstioGwVip: {{`{{ .ClusterClaim.spec.extraEnvs.systemIstioGwVip }}`}}
    {{`{{- else }}`}}
      systemIstioGwVip: {{ .Values.extraArgs.systemIstioGwVip }}
    {{`{{- end }}`}}
    {{`{{- if (index .ClusterClaim.spec.extraEnvs "systemIstioGwDomain") }}`}}
      systemIstioGwDomain: {{`{{ .ClusterClaim.spec.extraEnvs.systemIstioGwDomain }}`}}
    {{`{{- else }}`}}
      systemIstioGwDomain: {{ .Values.extraArgs.systemIstioGwDomain }}
    {{`{{- end }}`}}
    {{`{{- if (index .ClusterClaim.spec.extraEnvs "systemVmInsertVIP") }}`}}
      systemVmInsertVIP: {{`{{ .ClusterClaim.spec.extraEnvs.systemVmInsertVIP }}`}}
    {{`{{- else }}`}}
      systemVmInsertVIP: {{ .Values.extraArgs.systemVmInsertVIP }}
    {{`{{- end }}`}}   
    {{`{{- if (index .ClusterClaim.spec.extraEnvs "vmClusterReplicas") }}`}}
      vmClusterReplicas: {{`{{ .ClusterClaim.spec.extraEnvs.vmClusterReplicas }}`}}
    {{`{{- else }}`}}
      vmClusterReplicas: {{ .Values.extraArgs.vmClusterReplicas }}
    {{`{{- end }}`}}   
