apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: kube-state-metrics
spec:
  path: "kube-state-metrics"
  pluginName: helm-with-values
  repoURL: "https://blog.beget.com/kaas-helm-charts"
  version: "6.1.0-1"
  targetCluster: in-cluster
  targetNamespace: "beget-kube-state-metrics"
  variables:
    cluster_name: in-cluster
  initDependencies:
    - name: vm-operator
      criteria:
        - jsonPath: $.status.conditions[?(@.type=='Ready')].status
          operator: Equal
          value: "True"
  backend: 
    type: "argocd"
    namespace: "beget-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: kube-state-metrics
    - name: infra
      priority: 10
      matchLabels:
        addons.in-cloud.io/values: infra
        addons.in-cloud.io/addon: kube-state-metrics

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: kube-state-metrics-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: kube-state-metrics
spec:
  values: |
    kube-state-metrics:
      prometheusScrape: false
      metricLabelsAllowlist:
        - nodes=[node-group.beget.com/name]
      customLabels:
        in-cloud.io/clusterName: ""
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: kube-state-metrics-infra
  labels:
    addons.in-cloud.io/values: infra
    addons.in-cloud.io/addon: kube-state-metrics
spec:
  values: |
    kube-state-metrics:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: kube-state-metrics-cert-manager
  labels:
    addons.in-cloud.io/values: cert-manager
    addons.in-cloud.io/addon: kube-state-metrics
spec:
  values: |
    argocdPlugins:
      kustomize: true
    monitoring:
      secureService:
        enabled: true
        issuer:
          name: selfsigned-cluster-issuer

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: kube-state-metrics-vm-operator
  labels:
    addons.in-cloud.io/values: vm-operator
    addons.in-cloud.io/addon: kube-state-metrics
spec:
  values: |
    monitoring:
      enabled: true

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: kube-state-metrics
spec:
  rules:
    - name: cert-manager
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.status.conditions[?(@.type=='Ready')].status
          operator: Equal
          value: "True"
      selector:
        name: cert-manager
        priority: 20
        matchLabels:
          addons.in-cloud.io/values: cert-manager
          addons.in-cloud.io/addon: kube-state-metrics
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.status.conditions[?(@.type=='Ready')].status
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 30
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: kube-state-metrics

