{{- if .Values.networkPolicies.enabled }}

---
# Allow Hubble Relay to communicate with node-side relay peers.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-hubble-relay-to-host-and-remote-node-4244
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: hubble-relay
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - host
    - remote-node
    toPorts:
    - ports:
      - port: '4244'
        protocol: TCP
  description: Allows the required traffic between Hubble Relay and node-side relay
    peers on the declared port.

---
# Allow `hubble-ui` to talk to the Kubernetes API server.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-hubble-ui-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: hubble-ui
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from hubble-ui to the Kubernetes API server on 6443 for
    control-plane interactions.

---
# Allow `hubble-relay` to resolve DNS via CoreDNS.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-hubble-relay-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: hubble-relay
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
      rules:
        dns:
        - matchPattern: hubble-peer.{{ .Release.Namespace }}.svc.cluster.local
  description: Allows egress from hubble-relay to CoreDNS on 53 for DNS resolution.

---
# Allow `hubble-ui` to resolve DNS via CoreDNS.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-hubble-ui-to-coredns-53
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: hubble-ui
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: coredns
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-coredns
    toPorts:
    - ports:
      - port: '53'
        protocol: TCP
      - port: '53'
        protocol: UDP
      rules:
        dns:
        - matchPattern: '*'
  description: Allows egress from hubble-ui to CoreDNS on 53 for DNS resolution.

---
# Allow egress from `hubble-ui` to `hubble-relay`.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-hubble-ui-to-hubble-relay-4245
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: hubble-ui
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: hubble-relay
        k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
    toPorts:
    - ports:
      - port: '4245'
        protocol: TCP
  description: Allows egress from hubble-ui to hubble-relay on 4245.

---
# Allow Hubble UI to connect to Hubble Relay.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-hubble-ui-to-hubble-relay-4245
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: hubble-relay
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: hubble-ui
        k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
    toPorts:
    - ports:
      - port: '4245'
        protocol: TCP
  description: Allows traffic from Hubble UI to Hubble Relay on 4245 for the UI relay
    connection.

---
# Allow Hubble Relay to communicate with node-side relay peers.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-remote-node-to-hubble-relay-4245
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: hubble-relay
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEntities:
    - remote-node
    toPorts:
    - ports:
      - port: '4245'
        protocol: TCP
  description: Allows the required traffic between Hubble Relay and node-side relay
    peers on the declared port.
{{- end }}
