{{- if and .Values.monitoring.enabled (eq .Values.monitoring.type "VictoriaMetrics") }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ .Release.Name }}-operator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      monitoring.in-cloud.io/service: {{ .Release.Name }}-operator
  endpoints:
    - port: https-metrics
      path: /metrics
      scheme: HTTPS
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        serverName: {{ .Release.Name }}-operator
      {{- with .Values.monitoring.serviceScrapeConfig.metricRelabelConfigs }}
      metricRelabelConfigs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  jobLabel: cilium-operator
{{- end }}
