---
# Source: addonset/templates/addonsClient/kubeadm-resources/kubeadm-resources.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: kubeadm-resources
spec:
  chart: "kubeadm-resources-client-cp"
  pluginName: helm-with-values
  repoURL: "example.com"
  version: "0.1.1"
  releaseName: kubeadm-resources
  targetCluster: client
  targetNamespace: "example-kubeadm-resources"
  variables:
    cluster_name: client
  valuesSources:
    - name: parameters-client
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-client
        namespace: example-system
      extract:
        - as: clientServiceCidr
          jsonPath: .data.clientServiceCidr
        - as: cluster.host
          jsonPath: .data.clusterHost
        - as: cluster.port
          jsonPath: .data.clusterPort
        - as: cluster.name
          jsonPath: .data.clusterName
        - as: cluster.domain
          jsonPath: .data.clientClusterDomain
        - as: cluster.version
          jsonPath: .data.clientVersion
        - as: companyPrefix
          jsonPath: .data.companyPrefix
        - as: companyDomain
          jsonPath: .data.companyDomain
    - name: clientca
      sourceRef:
        apiVersion: v1
        kind: Secret
        name: client-ca
        namespace: example-system
      extract:
        - as: cluster.kubeCaCrtBase64
          jsonPath: .data["tls.crt"]
  initDependencies:
    - name: addons-operator
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: true
    - name: addonset
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: true
    - name: client-cp-control-plane
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/clusterName: client
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: client
      priority: 10
      matchLabels:
        addons.in-cloud.io/values: client
        addons.in-cloud.io/addon: kubeadm-resources
    - name: custom
      priority: 90
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: kubeadm-resources
---
# Source: addonset/templates/addonsClient/kubeadm-resources/kubeadm-resources.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: kubeadm-resources-client
  labels:
    addons.in-cloud.io/values: client
    addons.in-cloud.io/addon: kubeadm-resources
spec:
  values: |
    companyPrefix: {{ .Values.companyPrefix }}
    clusterInfo:
      clusterApiUrl: "https://{{ .Values.cluster.host }}:{{ .Values.cluster.port }}"
      clusterName: "{{ .Values.cluster.name }}"
      kubeCaCrtBase64: "{{ .Values.cluster.kubeCaCrtBase64 }}"
    kubeadmConfig:
      namespace: kube-system
      clusterConfiguration:
        clusterName: "{{ .Values.cluster.name }}"
        controlPlaneEndpoint: "{{ .Values.cluster.host }}:{{ .Values.cluster.port }}"
        networking:
          serviceSubnet: "{{ .Values.clientServiceCidr }}"
          dnsDomain: "{{ .Values.cluster.domain }}"
        kubernetesVersion: "{{ .Values.cluster.version }}"
    rbac:
      authExtraGroups: "system:bootstrappers:kubeadm:default-node-token"
