---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: vm-alertrules-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: vm-alertrules
spec:
  values: |
    additionalLabels:
      monitoring.in-cloud.io/vmrules: infra

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: vm-alertrules-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: vm-alertrules
spec:
  values: ""
