{{- if .Values.networkPolicies.enabled }}

---
# Allow vmagent to scrape `cert-manager-webhook` metrics.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-vmagent-to-cert-manager-webhook-11043
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: cert-manager-webhook
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '11043'
        protocol: TCP
  description: Allows ingress from vmagent to cert-manager-webhook on 11043 for metrics
    collection.

---
# Allow `cert-manager-webhook` to talk to the Kubernetes API server.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-cert-manager-webhook-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: cert-manager-webhook
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from cert-manager-webhook to the Kubernetes API server
    on 6443 for control-plane interactions.

---
# Allow `cert-manager-webhook` to talk to the Kubernetes API server.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-kube-apiserver-to-cert-manager-webhook-10250
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: cert-manager-webhook
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEntities:
    - kube-apiserver
    - remote-node
    toPorts:
    - ports:
      - port: '10250'
        protocol: TCP

---
# Allow vmagent to scrape `cert-manager-cainjector` metrics.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-vmagent-to-cert-manager-cainjector-11043
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: cert-manager-cainjector
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '11043'
        protocol: TCP
  description: Allows ingress from vmagent to cert-manager-cainjector on 11043 for
    metrics collection.

---
# Allow `cert-manager-cainjector` to talk to the Kubernetes API server.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-cert-manager-cainjector-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: cert-manager-cainjector
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from cert-manager-cainjector to the Kubernetes API server
    on 6443 for control-plane interactions.

---
# Allow vmagent to scrape `cert-manager` metrics.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-vmagent-to-cert-manager-11043
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: cert-manager
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '11043'
        protocol: TCP
  description: Allows ingress from vmagent to cert-manager on 11043 for metrics collection.

---
# Allow `cert-manager` to talk to the Kubernetes API server.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-cert-manager-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: cert-manager
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from cert-manager to the Kubernetes API server on 6443
    for control-plane interactions.

---
# Allow callbacks from the Kubernetes API server to `cert-manager`.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-kube-apiserver-to-cert-manager-6080
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: cert-manager
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6080'
        protocol: TCP
  description: Allows ingress from the Kubernetes API server to cert-manager on 6080
    for webhook or callback traffic.

{{- end }}