---
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: helm-inserter-vm-agent-additional-rbac
spec:
  path: "helm-inserter"
  pluginName: helm-with-values
  repoURL: "https://blog.beget.com/kaas-helm-charts"
  version: "0.2.5"
  targetCluster: in-cluster
  targetNamespace: "beget-vmagent"
  variables:
    cluster_name: in-cluster
{{- if .Values.clientClusterEnabled }}
  initDependencies:
    - name: client-cp-control-plane
      criteria:
        - jsonPath: $.status.deployed
          operator: Equal
          value: true
{{- end }}
  backend: 
    type: "argocd"
    namespace: "beget-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: infra
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: infra
        addons.in-cloud.io/addon: helm-inserter-vm-agent-additional-rbac

{{ .Files.Get "files/addonsMonitoring/vmAgentAdditionalRbac.yml" }}
