apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "vault-secret-operator.labels" . | nindent 4 }}
  name: {{ include "vault-secret-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  namespace: {{ .Release.Namespace }}
