{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "vault-secret-operator.labels" . | nindent 4 }}
  name: {{ include "vault-secret-operator.resourceName" (dict "suffix" "vaultsecretclaim-admin-role" "context" $) }}
rules:
  - apiGroups:
      - vault.in-cloud.io
    resources:
      - vaultsecretclaims
    verbs:
      - '*'
  - apiGroups:
      - vault.in-cloud.io
    resources:
      - vaultsecretclaims/status
    verbs:
      - get
{{- end }}
