{{- if .Values.addons.grafana.enabled }}
  {{- $clientContext := set (deepCopy .) "Values" (set (deepCopy .Values) "environment" "client") -}}
  
  {{- if .Values.addons.system.enabled }}
    {{- include "grafana.addon" . }}
  {{- end }}

  {{- .Files.Get "files/systemAddons/grafana/values.yml" | nindent 0 }}

  {{- include "grafana.phase" . }}

  {{- if eq .Values.environment "infra" }}
    {{- include "grafana.phase" $clientContext }}
  {{- end }}
{{- end }}