{{- if .Values.addonTemplates.prometheusnodeexporter.enabled }}

{{- tpl (.Files.Get "files/monitoringAddons/prometheus-node-exporter/prometheus-node-exporter-4.49.2-1/manifest.yaml") . }}

{{- end }}
