apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonTemplate
metadata:
  name: etcd-backup-snapshot
spec:
  template: |
    spec:
      chart: "etcd-backup-snapshot"
      pluginName: helm-with-values
      repoURL: "{{ .Values.companyExternalChartRegistry }}"
      version: "0.1.0"
      releaseName: etcd-backup-snapshot
      targetCluster: {{ "{{ .Values.spec.variables.cluster }}" }}
      targetNamespace: "{{ .Values.companyPrefix }}-etcd-backup-snapshot"
      variables:
        cluster_name: {{ "{{ .Values.spec.variables.cluster }}" }}
        dependency: "False"
      valuesSources:
        - name: parameters-client
          sourceRef:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-client
            namespace: {{ .Values.companyPrefix }}-system
          extract:
            - as: cluster.name
              jsonPath: .data.clusterName
            - as: etcdbackupAppArgsStorecontainer
              jsonPath: .data.etcdbackupAppArgsStorecontainer
            - as: etcdbackupS3AccessKey
              jsonPath: .data.etcdbackupS3AccessKey
            - as: etcdbackupS3SecretAccessKey
              jsonPath: .data.etcdbackupS3SecretAccessKey
            - as: etcdbackupS3SecretEndpoint
              jsonPath: .data.etcdbackupS3SecretEndpoint
            - as: companyPrefix
              jsonPath: .data.companyPrefix
            - as: companyDomain
              jsonPath: .data.companyDomain
      initDependencies: []
      backend: 
        finalizer: true
        type: "argocd"
        namespace: "{{ .Values.companyPrefix }}-argocd"
        project: "default"
        syncPolicy:
          automated:
            prune: true
            selfHeal: false
          managedNamespaceMetadata:
            labels:
              in-cloud.io/caBundle: approved
              in-cloud.io/clusterName: {{ "{{ .Values.spec.variables.cluster }}" }}
          syncOptions:
            - ApplyOutOfSyncOnly=true
            - CreateNamespace=true
      valuesSelectors:
        - name: default
          priority: 0
          matchLabels:
            addons.in-cloud.io/values: default
            addons.in-cloud.io/addon: etcd-backup-snapshot
        - name: custom
          priority: 90
          matchLabels:
            addons.in-cloud.io/values: {{ "{{ .Values.spec.valueLabels }}" }}
            addons.in-cloud.io/addon: etcd-backup-snapshot-client
        - name: immutable
          priority: 99
          matchLabels:
            addons.in-cloud.io/values: immutable
            addons.in-cloud.io/addon: etcd-backup-snapshot