{{- if .Values.monitoring.secureService.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-process-exporter-svc-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: prometheus-process-exporter-svc-tls
  duration: 8760h
  renewBefore: 720h
  commonName: {{ template "beget-prometheus-process-exporter.fullname" . }}
  dnsNames:
    - {{ template "beget-prometheus-process-exporter.fullname" . }}
    - {{ template "beget-prometheus-process-exporter.fullname" . }}.{{ .Release.Namespace }}
    - {{ template "beget-prometheus-process-exporter.fullname" . }}.{{ .Release.Namespace }}.svc
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    kind: {{ .Values.monitoring.secureService.issuer.kind }}
    name: {{ .Values.monitoring.secureService.issuer.name }}
{{- end }}
