{{- $vmstack := index .Values "victoria-metrics-k8s-stack" -}}

{{- if $vmstack.alertmanager.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alertmanager-alert-templates
  namespace: {{ .Release.Namespace }}
data:
  telegram_alerts.tmpl: |
    {{ define "emoji.status" -}}
    {{- if eq .Status "firing" -}}🚨{{- else -}}✅{{- end -}}
    {{- end }}

    {{ define "emoji.severity" -}}
    {{- $s := (index .CommonLabels "severity") -}}
    {{- if eq $s "critical" -}}🟥{{- else if eq $s "warning" -}}🟧{{- else if eq $s "info" -}}🟦{{- else -}}⬜{{- end -}}
    {{- end }}

    {{ define "title" -}}
    {{ template "emoji.status" . }} {{ template "emoji.severity" . }} <b>{{ .CommonLabels.alertname }}</b>
    {{- end }}

    {{ define "kv" -}}
    {{- range $k, $v := . -}}
    <b>{{ $k }}:</b> <code>{{ $v }}</code>
    {{ end -}}
    {{- end }}

    {{/* --- main message for Telegram --- */}}
    {{ define "tg.message" -}}
    {{ template "title" . }}

    <b>Status:</b> <code>{{ upper .Status }}</code>
    <b>Severity:</b> <code>{{ index .CommonLabels "severity" }}</code>
    {{- if (index .CommonLabels "cluster") }}
    <b>Cluster:</b> <code>{{ index .CommonLabels "cluster" }}</code>
    {{- end }}
    {{- if (index .CommonLabels "namespace") }}
    <b>Namespace:</b> <code>{{ index .CommonLabels "namespace" }}</code>
    {{- end }}
    {{- if (index .CommonLabels "service") }}
    <b>Service:</b> <code>{{ index .CommonLabels "service" }}</code>
    {{- end }}

    {{- if .CommonAnnotations.summary }}
    <b>Summary:</b> {{ .CommonAnnotations.summary }}
    {{- end }}
    {{- if .CommonAnnotations.description }}
    <b>Description:</b> {{ .CommonAnnotations.description }}
    {{- end }}
    {{- if .CommonAnnotations.runbook_url }}
    <b>Runbook:</b> {{ .CommonAnnotations.runbook_url }}
    {{- end }}
    {{- if .ExternalURL }}
    <b>Alertmanager:</b> {{ .ExternalURL }}
    {{- end }}

    <b>Alerts:</b> <code>{{ len .Alerts }}</code>
    {{ range .Alerts -}}
    —
    <b>Instance:</b> <code>{{ index .Labels "instance" }}</code>
    {{- if (index .Labels "pod") }} <b>Pod:</b> <code>{{ index .Labels "pod" }}</code>{{ end }}
    {{- if (index .Labels "node") }} <b>Node:</b> <code>{{ index .Labels "node" }}</code>{{ end }}
    {{- if .Annotations.summary }} 
    <b>•</b> {{ .Annotations.summary }}
    {{- end }}
    <b>StartsAt:</b> <code>{{ .StartsAt }}</code>
    {{- if ne $.Status "firing" }}
    <b>EndsAt:</b> <code>{{ .EndsAt }}</code>
    {{- end }}
    {{- if .GeneratorURL }}
    <b>Source:</b> {{ .GeneratorURL }}
    {{- end }}
    {{ end -}}
    {{- end }}
{{- end }}
