{{- $vmstack := index .Values "victoria-metrics-k8s-stack" -}}
{{- $vmalertmanagerName := dig "alertmanager" "spec" "configSecret" "vmalert-default-config" $vmstack  -}}

{{- if and $vmstack.alertmanager.enabled .Values.alertmanagerConfig.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $vmalertmanagerName }}
  namespace: {{ .Release.Namespace }}
stringData:
  alertmanager.yaml: |
    {{- with .Values.alertmanagerConfig.config }}
    {{- with .global }}
    global:
      {{ toYaml . | nindent 6 }}
    {{- end }}

    {{- with .templates }}
    templates:
      {{ toYaml . | nindent 6 }}
    {{- end }}

    {{- with .route }}
    route:
      receiver: {{ .receiver | quote }}
      {{- with .group_by }}
      group_by:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .group_wait }}
      group_wait: {{ . | quote }}
      {{- end }}
      {{- with .group_interval }}
      group_interval: {{ . | quote }}
      {{- end }}
      {{- with .repeat_interval }}
      repeat_interval: {{ . | quote }}
      {{- end }}

      {{- with .routes }}
      routes:
        {{- range $_, $route := . }}
        - matchers:
            {{ toYaml $route.matchers | nindent 12 }}
          receiver: {{ $route.receiver | quote }}
          {{- if hasKey $route "continue" }}
          continue: {{ $route.continue }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- if .receivers }}
    receivers:
      {{- range $name, $rcv := .receivers }}
      - name: {{ $name | quote }}
        {{- if and (kindIs "map" $rcv) (hasKey $rcv "type") }}
        {{- $type := $rcv.type }}
        {{- if $type }}
        {{ $type }}:
          {{- range $_, $cfg := $rcv.configs }}
            {{ toYaml $cfg | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- with .inhibit_rules }}
    inhibit_rules:
      {{ toYaml . | nindent 6 }}
    {{- end }}

    {{- with .time_intervals }}
    time_intervals:
      {{ toYaml . | nindent 6 }}
    {{- end }}

    {{- with .mute_time_intervals }}
    mute_time_intervals:
      {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
{{- end }}
