---
# Source: addonset/templates/addons/capi-cluster-class/addon.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: capi-cluster-class
spec:
  chart: "in-cloud-capi-template"
  pluginName: helm-with-values
  repoURL: "example.com"
  version: "0.1.6"
  targetCluster: in-cluster
  targetNamespace: "example-capi"
  variables:
    cluster_name: in-cluster
  valuesSources:
    - name: parameters-infra
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-infra
        namespace: example-system
      extract:
        - as: companyPrefix
          jsonPath: .data.companyPrefix
        - as: companyDomain
          jsonPath: .data.companyDomain
        - as: companyInternalDockerRegistry
          jsonPath: .data.companyInternalDockerRegistry
        - as: systemIstioGwDomain
          jsonPath: .data.systemIstioGwDomain
  initDependencies: 
    - name: cert-manager
      criteria:
        - jsonPath: $.status.conditions[?(@.type=='Ready')].status
          operator: Equal
          value: "True"
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: capi-cluster-class
    - name: custom
      priority: 90
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: capi-cluster-class
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: capi-cluster-class
---
# Source: addonset/templates/addons/capi-cluster-class/phase.infra.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: capi-cluster-class
spec:
  rules:
    - name: system
      criteria:
        - source:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-infra
            namespace: example-system
          jsonPath: $.data.systemEnabled
          operator: Equal
          value: "true"
      selector:
        name: system
        priority: 70
        matchLabels:
          addons.in-cloud.io/values: system
          addons.in-cloud.io/addon: capi-cluster-class
---
# Source: addonset/templates/addons/capi-cluster-class/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: capi-cluster-class-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: capi-cluster-class
spec:
  values: |
---
# Source: addonset/templates/addons/capi-cluster-class/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: capi-cluster-class-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: capi-cluster-class
spec:
  values: |
---
# Source: addonset/templates/addons/capi-cluster-class/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: capi-cluster-class-system
  labels:
    addons.in-cloud.io/values: system
    addons.in-cloud.io/addon: capi-cluster-class
spec:
  values: |
    
    
    companyDomain: example.com
    companyPrefix: example
    inCloud:
      serviceAccount:
        name: capi
    clusterResourcesEnabled: true
    capi:
      k8s:
        infrastructureType: example
        clusterInfrastructureTemplate:
          example:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: ExampleClusterTemplate
        machineInfrastructureTemplate:
          example:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: ExampleMachineTemplate
        controlPlane:
          components:
            kubelet:
              extraArgs:
                node-labels: "node-group.example.com/name={{`{{ .builtin.cluster.name }}`}}-control-plane"
        dataPlane:
          components:
            kubelet:
              extraArgs:
                node-labels: '{{`{{ printf "node-group.example.com/name=%s-%s" .clusterName .name | quote }}`}}'
        containerRuntime:
          mirrors:
            repos:
              docker.io:
                server: https://docker.io
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/registry-1-docker-io'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://registry-1.docker.io"
                    args:
                      skip_verify: false
                      priority: 2
              registry-1.docker.io:
                server: https://registry-1.docker.io
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/registry-1-docker-io'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://registry-1.docker.io"
                    args:
                      skip_verify: false
                      priority: 2
              europe-docker.pkg.dev:
                server: https://europe-docker.pkg.dev
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/europe-docker-pkg-dev'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://europe-docker.pkg.dev"
                    args:
                      skip_verify: false
                      priority: 2
              gcr.io:
                server: https://gcr.io
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/gcr-io'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://gcr.io"
                    args:
                      skip_verify: false
                      priority: 2
              ghcr.io:
                server: https://ghcr.io
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/ghcr-io'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://ghcr.io"
                    args:
                      skip_verify: false
                      priority: 2
              mirror.gcr.io:
                server: https://mirror.gcr.io
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/mirror-gcr-io'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://mirror.gcr.io"
                    args:
                      skip_verify: false
                      priority: 2
              public.ecr.aws:
                server: https://public.ecr.aws
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/public-ecr-aws'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://public.ecr.aws"
                    args:
                      skip_verify: false
                      priority: 2
              quay.io:
                server: https://quay.io
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/quay-io'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://quay.io"
                    args:
                      skip_verify: false
                      priority: 2
              registry.k8s.io:
                server: https://registry.k8s.io
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/registry-k8s-io'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://registry.k8s.io"
                    args:
                      skip_verify: false
                      priority: 2
              {{ .Values.companyInternalDockerRegistry }}:
                server: https://{{ .Values.companyInternalDockerRegistry }}
                mirrors:
                  - mirror: '{{ "{{ if index . `containerdMirrorUrl` }}{{ .containerdMirrorUrl }}{{ else }}" }}{{ .Values.systemIstioGwDomain }}{{ "{{ end }}" }}/repository/registry-example-ru'
                    args:
                      skip_verify: false
                      ca: "/etc/kubernetes/pki/ca-oidc.crt"
                      priority: 1
                  - mirror: "https://{{ .Values.companyInternalDockerRegistry }}"
                    args:
                      skip_verify: false
                      priority: 2
