{{- if eq .Values.capi.k8s.controlPlaneType "kubeadm" }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlaneTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Values.capi.k8s.controlPlaneType }}-control-plane-template
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      rollout:
        before:
          certificatesExpiryDays: 180

      kubeadmConfigSpec:
        users:
          - name: capv
            sshAuthorizedKeys:
              - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPemirhenH3JKGPs6UNRDj2rsu5LmTEmu8d87XgaP89x dk@dobryKot.global.bcs"
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash

        clusterConfiguration:
          apiServer:
            extraVolumes:
              - name: k8s-audit
                hostPath: /var/log/kubernetes/audit/
                mountPath: /var/log/kubernetes/audit/
                pathType: DirectoryOrCreate

          controllerManager:
            extraArgs:
              - name: bind-address
                value: "127.0.0.1"
              - name: secure-port
                value: "10257"

          scheduler:
            extraArgs:
              - name: bind-address
                value: "127.0.0.1"
              - name: secure-port
                value: "10259"
              - name: leader-elect
                value: "true"

          etcd:
            local:
              imageRepository: registry.k8s.io
              dataDir: /var/lib/etcd

          imageRepository: registry.k8s.io

        files:
          - content: |
              ##### FIX PROBLEM CLUSTER API =( 
              ###->
              error computing the desired state of the Cluster topology: failed to
              apply patches: failed to apply patches for patch
              "customKubeadmControlPlaneFiles": failed to apply patch: error applying
              json patch (RFC6902): add operation does not apply: doc is missing path:
              "/spec/template/spec/kubeadmConfigSpec/files/-": missing value
              
              #### Ошибка возникает, потому что если блок files будет пустым массивом, 
              #### то при развертывании этот блок будет удален из спецификации, и патч выдаст ошибку.
              #### ЭТОТ КОНФИГ ОТСЮДА НЕ УДАЛЯТЬ!!!!! =)
            owner: root:root
            path: /tmp/tempory_file
            permissions: "0644"

          - path: /etc/kubernetes/patches/kube-scheduler+json.json
            owner: root:root
            permissions: "0644"
            content: |
              [
                {
                  "op": "add",
                  "path": "/spec/containers/-",
                  "value": {
                    "name": "rbac-proxy",
                    "image": "quay.io/brancz/kube-rbac-proxy:v0.21.0",
                    "args": [
                      "--secure-listen-address=0.0.0.0:11043",
                      "--upstream=https://127.0.0.1:10259",
                      "--tls-cert-file=/etc/kubernetes/pki/rbac-proxy-server.crt",
                      "--tls-private-key-file=/etc/kubernetes/pki/rbac-proxy-server.key",
                      "--kubeconfig=/etc/kubernetes/rbac-proxy.conf",
                      "--auth-header-fields-enabled",
                      "--v=2"
                    ],
                    "ports": [
                      {
                        "name": "https-metrics",
                        "containerPort": 11043,
                        "protocol": "TCP"
                      }
                    ],
                    "resources": {
                      "requests": {
                        "memory": "32Mi",
                        "cpu": "10m"
                      },
                      "limits": {
                        "memory": "64Mi",
                        "cpu": "50m"
                      }
                    },
                    "volumeMounts": [
                      {
                        "name": "rbac-proxy-server-crt",
                        "mountPath": "/etc/kubernetes/pki/rbac-proxy-server.crt",
                        "readOnly": true
                      },
                      {
                        "name": "rbac-proxy-server-key",
                        "mountPath": "/etc/kubernetes/pki/rbac-proxy-server.key",
                        "readOnly": true
                      },
                      {
                        "name": "rbac-proxy-client-crt",
                        "mountPath": "/etc/kubernetes/pki/rbac-proxy-client.crt",
                        "readOnly": true
                      },
                      {
                        "name": "rbac-proxy-client-key",
                        "mountPath": "/etc/kubernetes/pki/rbac-proxy-client.key",
                        "readOnly": true
                      },
                      {
                        "name": "rbac-proxy-kubeconfig",
                        "mountPath": "/etc/kubernetes/rbac-proxy.conf",
                        "readOnly": true
                      }
                    ]
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-server-crt",
                    "hostPath": {
                      "path": "/etc/kubernetes/pki/rbac-proxy-server.crt",
                      "type": "File"
                    }
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-server-key",
                    "hostPath": {
                      "path": "/etc/kubernetes/pki/rbac-proxy-server.key",
                      "type": "File"
                    }
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-client-crt",
                    "hostPath": {
                      "path": "/etc/kubernetes/pki/rbac-proxy-client.crt",
                      "type": "File"
                    }
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-client-key",
                    "hostPath": {
                      "path": "/etc/kubernetes/pki/rbac-proxy-client.key",
                      "type": "File"
                    }
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-kubeconfig",
                    "hostPath": {
                      "path": "/etc/kubernetes/rbac-proxy.conf",
                      "type": "File"
                    }
                  }
                }
              ]

          - path: /etc/kubernetes/patches/kube-controller-manager+json.json
            owner: root:root
            permissions: "0644"
            content: |
              [
                {
                  "op": "add",
                  "path": "/spec/containers/-",
                  "value": {
                    "name": "rbac-proxy",
                    "image": "quay.io/brancz/kube-rbac-proxy:v0.21.0",
                    "args": [
                      "--secure-listen-address=0.0.0.0:11044",
                      "--upstream=https://127.0.0.1:10257",
                      "--tls-cert-file=/etc/kubernetes/pki/rbac-proxy-server.crt",
                      "--tls-private-key-file=/etc/kubernetes/pki/rbac-proxy-server.key",
                      "--kubeconfig=/etc/kubernetes/rbac-proxy.conf",
                      "--auth-header-fields-enabled",
                      "--v=2"
                    ],
                    "ports": [
                      {
                        "name": "https-metrics",
                        "containerPort": 11044,
                        "protocol": "TCP"
                      }
                    ],
                    "resources": {
                      "requests": {
                        "memory": "32Mi",
                        "cpu": "10m"
                      },
                      "limits": {
                        "memory": "64Mi",
                        "cpu": "50m"
                      }
                    },
                    "volumeMounts": [
                      {
                        "name": "rbac-proxy-server-crt",
                        "mountPath": "/etc/kubernetes/pki/rbac-proxy-server.crt",
                        "readOnly": true
                      },
                      {
                        "name": "rbac-proxy-server-key",
                        "mountPath": "/etc/kubernetes/pki/rbac-proxy-server.key",
                        "readOnly": true
                      },
                      {
                        "name": "rbac-proxy-client-crt",
                        "mountPath": "/etc/kubernetes/pki/rbac-proxy-client.crt",
                        "readOnly": true
                      },
                      {
                        "name": "rbac-proxy-client-key",
                        "mountPath": "/etc/kubernetes/pki/rbac-proxy-client.key",
                        "readOnly": true
                      },
                      {
                        "name": "rbac-proxy-kubeconfig",
                        "mountPath": "/etc/kubernetes/rbac-proxy.conf",
                        "readOnly": true
                      }
                    ]
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-server-crt",
                    "hostPath": {
                      "path": "/etc/kubernetes/pki/rbac-proxy-server.crt",
                      "type": "File"
                    }
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-server-key",
                    "hostPath": {
                      "path": "/etc/kubernetes/pki/rbac-proxy-server.key",
                      "type": "File"
                    }
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-client-crt",
                    "hostPath": {
                      "path": "/etc/kubernetes/pki/rbac-proxy-client.crt",
                      "type": "File"
                    }
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-client-key",
                    "hostPath": {
                      "path": "/etc/kubernetes/pki/rbac-proxy-client.key",
                      "type": "File"
                    }
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/volumes/-",
                  "value": {
                    "name": "rbac-proxy-kubeconfig",
                    "hostPath": {
                      "path": "/etc/kubernetes/rbac-proxy.conf",
                      "type": "File"
                    }
                  }
                }
              ]

        format: cloud-config

        initConfiguration:
          localAPIEndpoint:
            advertiseAddress: 127.0.0.1
          nodeRegistration:
            imagePullPolicy: IfNotPresent
          patches:
            directory: /etc/kubernetes/patches
          skipPhases:
            - addon

        joinConfiguration:
          controlPlane:
            localAPIEndpoint:
              advertiseAddress: 127.0.0.1
          nodeRegistration:
            imagePullPolicy: IfNotPresent
          patches:
            directory: /etc/kubernetes/patches

      machineTemplate:
        spec:
          deletion:
            nodeDeletionTimeoutSeconds: 120
            nodeDrainTimeoutSeconds: 60
            nodeVolumeDetachTimeoutSeconds: 60
{{- end }}
