---
# Source: addonset/templates/addons/worker-group-claim-operator/addon.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: worker-group-claim-operator
spec:
  chart: "worker-group-claim-operator"
  repoURL: "example.com"
  version: "0.1.1"
  targetCluster: in-cluster
  targetNamespace: "example-worker-group-claim-operator"
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: worker-group-claim-operator
    - name: custom
      priority: 95
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: worker-group-claim-operator
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: worker-group-claim-operator
---
# Source: addonset/templates/addons/worker-group-claim-operator/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: worker-group-claim-operator-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: worker-group-claim-operator
spec:
  values: |
    companyPrefix: {{ .Values.companyPrefix }}
    manager:
      image:
        repository: prorobotech/worker-group-claim-operator
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
---
# Source: addonset/templates/addons/worker-group-claim-operator/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: worker-group-claim-operator-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: worker-group-claim-operator
spec:
  values: |
