---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: svc-hub-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: svc-hub  
spec:
  values: |
    hub:
      image:
        repository: {{ .Values.companyInternalDockerRegistry }}/golang/svc-hub
      config:
        plugin:
          rabbit:
            host: "{{ .Values.svcHubRabbitHost }}"
            port: 5672
            username: "{{ .Values.svcHubRabbitUsername }}"
            password: "{{ .Values.svcHubRabbitPassword }}"
            virtual_host: "{{ .Values.svcHubRabbitVirtualHost }}"
            exchange: global-events
        sd:
          tags: [{{ .Values.companyPrefix }}, production, k8s]
      env:
        CONSUL_HTTP_ADDR: consul.{{ .Values.companyPrefix }}:8500
    imagePullSecrets:
      - name: regcred

---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: svc-hub-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: svc-hub
spec:
  values: ""
