---
# Source: addonset/templates/systemAddons/grafana-operator/grafana-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: grafana-operator
spec:
  chart: "grafana-operator"
  pluginName: helm-with-values
  repoURL: "example.com"
  version: "5.18.0-1"
  targetCluster: in-cluster
  targetNamespace: "example-grafana-operator"
  variables:
    cluster_name: in-cluster
    dependency: "True"
  backend:
    finalizer: true
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - ServerSideApply=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: grafana-operator
    - name: custom
      priority: 90
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: grafana-operator
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: grafana-operator
---
# Source: addonset/templates/systemAddons/grafana-operator/grafana-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: grafana-operator
spec:
  rules:
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 30
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: grafana-operator
---
# Source: addonset/templates/systemAddons/grafana-operator/grafana-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonPhase
metadata:
  name: grafana-operator-client
spec:
  rules:
    - name: vm-operator
      criteria:
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: cert-manager-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator-client
          jsonPath: $.status.deployed
          operator: Equal
          value: true
          keep: false
        - source:
            apiVersion: addons.in-cloud.io/v1alpha1
            kind: Addon
            name: vm-operator-client
          jsonPath: $.spec.variables.dependency
          operator: Equal
          value: "True"
      selector:
        name: vm-operator
        priority: 30
        matchLabels:
          addons.in-cloud.io/values: vm-operator
          addons.in-cloud.io/addon: grafana-operator
---
# Source: addonset/templates/systemAddons/grafana-operator/grafana-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: grafana-operator-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: grafana-operator
spec:
  values: |
    grafana-operator:
      namespaceScope: false
      priorityClassName: system-cluster-critical
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 500m
          memory: 750Mi
---
# Source: addonset/templates/systemAddons/grafana-operator/grafana-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: grafana-operator-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: grafana-operator
spec:
  values: ""
---
# Source: addonset/templates/systemAddons/grafana-operator/grafana-operator.yml
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: grafana-operator-vm-operator
  labels:
    addons.in-cloud.io/values: vm-operator
    addons.in-cloud.io/addon: grafana-operator
spec:
  values: |
    argocdPlugins:
      kustomize: true
    monitoring:
      enabled: true
      secureService:
        enabled: true
        issuer:
          name: selfsigned-cluster-issuer
