---
# Source: addonset/templates/addons/svc-hub/addon.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: Addon
metadata:
  name: svc-hub
spec:
  chart: "svc-hub"
  pluginName: helm-with-values
  repoURL: "example.com"
  version: "0.1.0"
  targetCluster: in-cluster
  targetNamespace: "example-svc-hub"
  variables:
    cluster_name: in-cluster
    dependency: "True"
  valuesSources: 
    - name: parameters
      sourceRef:
        apiVersion: v1
        kind: ConfigMap
        name: parameters-infra
        namespace: example-system
      extract:
        - as: companyPrefix
          jsonPath: .data.companyPrefix
        - as: svcHubRabbitUsername
          jsonPath: .data.svcHubRabbitUsername
        - as: svcHubRabbitPassword
          jsonPath: .data.svcHubRabbitPassword
        - as: svcHubRabbitHost
          jsonPath: .data.svcHubRabbitHost
        - as: svcHubRabbitVirtualHost
          jsonPath: .data.svcHubRabbitVirtualHost
        - as: companyInternalDockerRegistry
          jsonPath: .data.companyInternalDockerRegistry
  backend: 
    finalizer: true 
    type: "argocd"
    namespace: "example-argocd"
    project: "default"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          in-cloud.io/caBundle: approved
          in-cloud.io/clusterName: infra
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
  valuesSelectors:
    - name: default
      priority: 0
      matchLabels:
        addons.in-cloud.io/values: default
        addons.in-cloud.io/addon: svc-hub
    - name: custom
      priority: 95
      matchLabels:
        addons.in-cloud.io/values: custom
        addons.in-cloud.io/addon: svc-hub
    - name: immutable
      priority: 99
      matchLabels:
        addons.in-cloud.io/values: immutable
        addons.in-cloud.io/addon: svc-hub
---
# Source: addonset/templates/addons/svc-hub/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: svc-hub-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: svc-hub
spec:
  values: |
    hub:
      image:
        repository: {{ .Values.companyInternalDockerRegistry }}/golang/svc-hub
      config:
        plugin:
          rabbit:
            host: "{{ .Values.svcHubRabbitHost }}"
            port: 5672
            username: "{{ .Values.svcHubRabbitUsername }}"
            password: "{{ .Values.svcHubRabbitPassword }}"
            virtual_host: "{{ .Values.svcHubRabbitVirtualHost }}"
            exchange: global-events
        sd:
          tags: [{{ .Values.companyPrefix }}, production, k8s]
      env:
        CONSUL_HTTP_ADDR: consul.{{ .Values.companyPrefix }}:8500
    imagePullSecrets:
      - name: regcred
---
# Source: addonset/templates/addons/svc-hub/values.yaml.gotmpl
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: svc-hub-immutable
  labels:
    addons.in-cloud.io/values: immutable
    addons.in-cloud.io/addon: svc-hub
spec:
  values: |
