{{ if .Values.networkPolicies.redis.enabled }}

---
# Allow `argocd-redis` to talk to the Kubernetes API server (infra).
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-argocd-redis-to-kube-apiserver-6443
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.redis.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  ingress:
  - {}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from argocd-redis to the Kubernetes API server
    on 6443 for control-plane interactions.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-argocd-server-to-redis-6379
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.redis.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  egress:
  - {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.server.serviceAccountName" . }}
        k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
    toPorts:
    - ports:
      - port: '6379'
        protocol: TCP
  description: Allows ingress from redis to argocd-server on 6379 for data storage.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-argocd-repo-server-to-redis-6379
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.redis.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  egress:
  - {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.repoServer.serviceAccountName" . }}
        k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
    toPorts:
    - ports:
      - port: '6379'
        protocol: TCP
  description: Allows ingress from redis to argocd-repo-server on 6379 for data storage.

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-argocd-application-controller-to-redis-6379
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.redis.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  egress:
  - {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.controller.serviceAccountName" . }}
        k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
    toPorts:
    - ports:
      - port: '6379'
        protocol: TCP
  description: Allows ingress from argocd-application-controller to redis on 6379 for data storage.

---
# Allow vmagent to scrape `argocd-redis` metrics.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-vmagent-to-argocd-redis-11043
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "argo-cd-wrapper.redis.serviceAccountName" . }}
      k8s:io.kubernetes.pod.namespace: {{ include  "argo-cd-wrapper.namespace" . }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '11043'
        protocol: TCP
  egress:
  - {}
  description: Allows ingress from vmagent to argocd-redis on 11043 for
    metrics collection.

{{- end }}