{{- $argocd := index .Values "argo-cd" -}}

{{- if and $argocd.redis.enabled .Values.monitoring.enabled (eq .Values.monitoring.type "VictoriaMetrics") }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ template "argo-cd-wrapper.redis.fullname" . }}
  namespace: {{ include  "argo-cd-wrapper.namespace" . }}
spec:
  selector:
    matchLabels:
      monitoring.in-cloud.io/service: {{ template "argo-cd-wrapper.redis.fullname" . }}
  endpoints:
    - port: https-metrics
      path: /metrics
      scheme: HTTPS
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        serverName: {{ template "argo-cd-wrapper.redis.fullname" . }}-metrics
  jobLabel: argocd-redis
{{- end }}
