{{- if .Values.networkPolicies.enabled }}
---
# Allow `addons-operator` to talk to the Kubernetes API server.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-{{ .Release.Name }}-to-kube-apiserver-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "addon-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from addons-operator to the Kubernetes API server on
    6443 for control-plane interactions.

---
# Allow ingress from `kube-apiserver-and-remote-node` to `addons-operator`.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-kapi-and-rnode-to-{{ .Release.Name }}-9443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "addon-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  ingress:
  - fromEntities:
    - kube-apiserver
    - remote-node
    toPorts:
    - ports:
      - port: '9443'
        protocol: TCP
  description: Allows ingress from kube-apiserver-and-remote-node to addons-operator
    on 9443.

---
# Allow vmagent to scrape `addons-operator` metrics.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-addons-operator-from-vm-agent-8443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "addon-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
      k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.policy.serviceaccount: vmagent-vmagent
        k8s:io.kubernetes.pod.namespace: {{ .Values.companyPrefix }}-vmagent
    toPorts:
    - ports:
      - port: '8443'
        protocol: TCP
  description: Allows ingress to addons-operator from vmagent on 8443 for metrics collection.

{{- end }}