{{- if .Values.networkPolicies.systemEnabled }}
---
# Allow `addons-operator` to reach external (world) workload API servers.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-{{ .Release.Name }}-to-world-6443
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:io.cilium.k8s.policy.serviceaccount: {{ include "addon-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  egress:
  - toCIDR:
    - 0.0.0.0/0
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  description: Allows egress from addons-operator to external workload cluster API
    servers on 6443.
{{- end }}
