---
apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonValue
metadata:
  name: clickhouse-vmstorage-default
  labels:
    addons.in-cloud.io/values: default
    addons.in-cloud.io/addon: clickhouse-vmstorage
spec:
  values: |
    clickhouse:
      resources:
        limits:
          cpu: 4
          memory: 8Gi

      keeper:
        resources:
          limits:
            cpu: 1
            memory: 1Gi
