apiVersion: addons.in-cloud.io/v1alpha1
kind: AddonTemplate
metadata:
  name: cilium
spec:
  template: |
    spec:
      chart: "cilium"
      pluginName: helm-with-values
      repoURL: "{{ .Values.companyExternalChartRegistry }}"
      version: "1.18.5-1"
      releaseName: cilium
      targetCluster: {{ "{{ .Values.spec.variables.cluster }}" }}
      targetNamespace: "{{ .Values.companyPrefix }}-cilium"
      variables:
        cluster_name: {{ "{{ .Values.spec.variables.cluster }}" }}
        dependency: "False"
      valuesSources:
        - name: parameters-client
          sourceRef:
            apiVersion: v1
            kind: ConfigMap
            name: parameters-client
            namespace: {{ .Values.companyPrefix }}-system
          extract:
            - as: cluster.host
              jsonPath: .data.clusterHost
            - as: cluster.name
              jsonPath: .data.clusterName
            - as: cluster.port
              jsonPath: .data.clusterPort
            - as: podCidr
              jsonPath: .data.podCidr
            - as: podCidrMaskSize
              jsonPath: .data.podCidrMaskSize
            - as: companyPrefix
              jsonPath: .data.companyPrefix
            - as: companyDomain
              jsonPath: .data.companyDomain
      backend: 
        finalizer: true
        type: "argocd"
        namespace: "{{ .Values.companyPrefix }}-argocd"
        project: "default"
        syncPolicy:
          automated:
            prune: true
            selfHeal: false
          managedNamespaceMetadata:
            labels:
              in-cloud.io/caBundle: approved
              in-cloud.io/clusterName: {{ "{{ .Values.spec.variables.cluster }}" }}
          syncOptions:
            - ApplyOutOfSyncOnly=true
            - CreateNamespace=true
        ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: Service
          jqPathExpressions:
            - .spec.ports[]?.nodePort
      valuesSelectors:
        - name: default
          priority: 0
          matchLabels:
            addons.in-cloud.io/values: default
            addons.in-cloud.io/addon: cilium
        - name: custom
          priority: 90
          matchLabels:
            addons.in-cloud.io/values: {{ "{{ .Values.spec.valueLabels }}" }}
            addons.in-cloud.io/addon: cilium-client
        - name: client
          priority: 95
          matchLabels:
            addons.in-cloud.io/values: client
            addons.in-cloud.io/addon: cilium
        - name: immutable
          priority: 99
          matchLabels:
            addons.in-cloud.io/values: immutable
            addons.in-cloud.io/addon: cilium